pt.lsts.asa.managers.SoundManager Class Reference
Public Member Functions
int getMaxVolume ()
boolean checkMute ()
int getCurrentVolume ()
void setCurrentVolume (int val)
void setVolumeControlChanger (VerticalSeekBar volControl, final AudioManager audioManager)
void mute ()
void unmute ()
Static Public Member Functions
static SoundManager getInstance ()
Private Member Functions
SoundManager ()
Private Attributes
AudioManager audioManager
Static Private Attributes
static SoundManager instance = null
Detailed Description
Definition at line 9 of file SoundManager.java.
Constructor & Destructor Documentation
pt.lsts.asa.managers.SoundManager.SoundManager () [private]
Definition at line 18 of file SoundManager.java.
References pt.lsts.asa.App.getAudioManager().
Referenced by pt.lsts.asa.managers.SoundManager.getInstance().
Member Function Documentation
boolean pt.lsts.asa.managers.SoundManager.checkMute ()
Definition at line 28 of file SoundManager.java.
References pt.lsts.asa.managers.SoundManager.getCurrentVolume().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute(), and pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon().
int pt.lsts.asa.managers.SoundManager.getCurrentVolume ()
Definition at line 34 of file SoundManager.java.
Referenced by pt.lsts.asa.fragments.SoundControlFragment.adjustVolumeBarAndIcon(), pt.lsts.asa.managers.SoundManager.checkMute(), pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
static SoundManager pt.lsts.asa.managers.SoundManager.getInstance () [static]
Definition at line 22 of file SoundManager.java.
References pt.lsts.asa.managers.SoundManager.instance, and pt.lsts.asa.managers.SoundManager.SoundManager().
Referenced by pt.lsts.asa.feedback.CallOut.CallOut().
int pt.lsts.asa.managers.SoundManager.getMaxVolume ()
Definition at line 14 of file SoundManager.java.
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl().
void pt.lsts.asa.managers.SoundManager.mute ()
Definition at line 67 of file SoundManager.java.
Referenced by pt.lsts.asa.fragments.SoundControlFragment.mute().
void pt.lsts.asa.managers.SoundManager.setCurrentVolume (int val)
Definition at line 41 of file SoundManager.java.
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setVolumeControlChanger(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
void pt.lsts.asa.managers.SoundManager.setVolumeControlChanger (VerticalSeekBar volControl, final AudioManager audioManager)
Definition at line 45 of file SoundManager.java.
References pt.lsts.asa.managers.SoundManager.unmute().
void pt.lsts.asa.managers.SoundManager.unmute ()
Definition at line 71 of file SoundManager.java.
Referenced by pt.lsts.asa.managers.SoundManager.setVolumeControlChanger(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
Member Data Documentation
AudioManager pt.lsts.asa.managers.SoundManager.audioManager [private]
Definition at line 12 of file SoundManager.java.
SoundManager pt.lsts.asa.managers.SoundManager.instance = null [static], [private]
Definition at line 11 of file SoundManager.java.
Referenced by pt.lsts.asa.managers.SoundManager.getInstance().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/managers/SoundManager.java