pt.lsts.asa.ASA Class Reference
Public Member Functions
void addSubscriber (IMCSubscriber sub)
void addSubscriber (IMCSubscriber sub, String[] abbrevNameList)
void initBroadcast ()
void initSystemsList ()
void initAnnouncer ()
void initGPSManager (Context context)
void initPreferences (Context context)
void initIMCManager ()
void initSubscribers (Context context)
void addInitialSubscribers ()
void load ()
void addLblSubscriber ()
void start ()
void pause ()
Sys getActiveSys ()
void setActiveSys (Sys activeS)
IMCManager getIMCManager ()
SystemList getSystemList ()
GPSManager getGpsManager ()
SensorManager getSensorManager ()
LblBeaconList getLblBeaconList ()
CallOut getCallOut ()
Bus getBus ()
void setCallOut (CallOut callOut)
void addMainSysChangeListener (MainSysChangeListener listener)
void removeMainSysChangeListener (MainSysChangeListener listener)
SharedPreferences getPrefs ()
boolean isStarted ()
int getNextRequestId ()
void addPreferencesListenner (OnSharedPreferenceChangeListener listener)
Static Public Member Functions
static ASA getInstance (Context context)
static ASA getInstance ()
static Context getContext ()
Public Attributes
boolean UIThread = false
SystemList sysList
SystemListIMCSubscriber systemListIMCSubscriber
String broadcastAddress
boolean started = false
SharedPreferences sharedPreferences
Static Public Attributes
static Announcer announcer
static AccuSmsHandler smsHandler
static AccuSmsHandlerIMCSubscriber accuSmsHandlerIMCSubscriber
static GPSManager gpsManager
static HeartbeatVibrator hearbeatVibrator
static HeartbeatVibratorIMCSubscriber heartbeatVibratorIMCSubscriber
static Heart heart
static LblBeaconList lblBeaconList
static LblBeaconListIMCSubscriber lblBeaconListIMCSubscriber
static SensorManager sensorManager
Private Member Functions
ASA (Context context)
Static Private Member Functions
static void notifyMainSysChange ()
Private Attributes
CallOut callOut
Bus bus
Static Private Attributes
static final String TAG = `ASA`
static Context context
static ASA instance
static Sys activeSys
static IMCManager imcManager
static ArrayList< MainSysChangeListener > mainSysChangeListeners
static Integer requestId = 0xFFFF
Detailed Description
Global Singleton of ASA and necessary components initiated in App extension of Application. (Fork from ACCU)
Definition at line 41 of file ASA.java.
Constructor & Destructor Documentation
pt.lsts.asa.ASA.ASA (Context context) [private]
Definition at line 75 of file ASA.java.
References pt.lsts.asa.ASA.context, pt.lsts.asa.ASA.initAnnouncer(), pt.lsts.asa.ASA.initBroadcast(), pt.lsts.asa.ASA.initGPSManager(), pt.lsts.asa.ASA.initIMCManager(), pt.lsts.asa.ASA.initPreferences(), pt.lsts.asa.ASA.initSubscribers(), and pt.lsts.asa.ASA.initSystemsList().
Referenced by pt.lsts.asa.ASA.getInstance().
Member Function Documentation
void pt.lsts.asa.ASA.addInitialSubscribers ()
Definition at line 139 of file ASA.java.
References pt.lsts.asa.ASA.addSubscriber(), pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.SUBSCRIBED_MSGS, pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.SUBSCRIBED_MSGS, and pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.SUBSCRIBED_MSGS.
Referenced by pt.lsts.asa.ASA.initSubscribers().
void pt.lsts.asa.ASA.addLblSubscriber ()
Definition at line 152 of file ASA.java.
Referenced by pt.lsts.asa.ASA.load().
void pt.lsts.asa.ASA.addMainSysChangeListener (MainSysChangeListener listener)
Definition at line 245 of file ASA.java.
void pt.lsts.asa.ASA.addPreferencesListenner (OnSharedPreferenceChangeListener listener)
Definition at line 291 of file ASA.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
void pt.lsts.asa.ASA.addSubscriber (IMCSubscriber sub)
Definition at line 87 of file ASA.java.
References pt.lsts.asa.managers.IMCManager.addSubscriberToAllMessages().
Referenced by pt.lsts.asa.ASA.addInitialSubscribers(), pt.lsts.asa.fragments.ManualIndicatorsFragment.initIMCSubscriber(), pt.lsts.asa.fragments.GmapFragment.initIMCSubscriber(), and pt.lsts.asa.feedback.CallOut.initImcSubscribers().
void pt.lsts.asa.ASA.addSubscriber (IMCSubscriber sub, String[] abbrevNameList)
Definition at line 90 of file ASA.java.
References pt.lsts.asa.managers.IMCManager.addSubscriber().
Sys pt.lsts.asa.ASA.getActiveSys ()
Definition at line 197 of file ASA.java.
References pt.lsts.asa.ASA.activeSys.
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.util.IMCUtils.isMsgFromActive(), pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), pt.lsts.asa.managers.IMCManager.sendToActiveSys(), pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng(), pt.lsts.asa.fragments.GmapFragment.setActiveSysPsi(), pt.lsts.asa.activities.MainActivity.test2(), and pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
Bus pt.lsts.asa.ASA.getBus ()
Definition at line 236 of file ASA.java.
References pt.lsts.asa.ASA.bus.
Referenced by pt.lsts.asa.feedback.CallOut.CallOut(), pt.lsts.asa.fragments.ManualIndicatorsFragment.initPreferencesListenner(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), and pt.lsts.asa.settings.Settings.putString().
CallOut pt.lsts.asa.ASA.getCallOut ()
Definition at line 232 of file ASA.java.
References pt.lsts.asa.ASA.callOut.
static Context pt.lsts.asa.ASA.getContext () [static]
Definition at line 287 of file ASA.java.
References pt.lsts.asa.ASA.context.
Referenced by pt.lsts.asa.activities.ManualActivity.onCreate(), pt.lsts.asa.util.AndroidUtil.showToastLong(), and pt.lsts.asa.util.AndroidUtil.showToastShort().
GPSManager pt.lsts.asa.ASA.getGpsManager ()
Definition at line 218 of file ASA.java.
References pt.lsts.asa.ASA.gpsManager.
Referenced by pt.lsts.asa.comms.Announcer.start(), and pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce().
IMCManager pt.lsts.asa.ASA.getIMCManager ()
Definition at line 208 of file ASA.java.
References pt.lsts.asa.ASA.imcManager.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
static ASA pt.lsts.asa.ASA.getInstance (Context context) [static]
Definition at line 184 of file ASA.java.
References pt.lsts.asa.ASA.ASA(), and pt.lsts.asa.ASA.instance.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos(), pt.lsts.asa.ASA.addPreferencesListenner(), pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.feedback.CallOut.CallOut(), pt.lsts.asa.activities.MainActivity.chooseActiveSystem(), pt.lsts.asa.settings.Settings.clear(), pt.lsts.asa.fragments.SystemListFragment.colorItems(), pt.lsts.asa.activities.MainActivity.createChooseActiveSystemDialog(), pt.lsts.asa.settings.Settings.exists(), pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.settings.Settings.getBoolean(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getSharedPreferences(), pt.lsts.asa.settings.Settings.getString(), pt.lsts.asa.settings.Settings.getStrings(), pt.lsts.asa.settings.Settings.getType(), pt.lsts.asa.fragments.ManualIndicatorsFragment.initIMCSubscriber(), pt.lsts.asa.fragments.GmapFragment.initIMCSubscriber(), pt.lsts.asa.feedback.CallOut.initImcSubscribers(), pt.lsts.asa.fragments.ManualIndicatorsFragment.initPreferencesListenner(), pt.lsts.asa.util.IMCUtils.isMsgFromActive(), pt.lsts.asa.App.onCreate(), pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive(), pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), pt.lsts.asa.activities.MainActivity.pauseASA(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putFullString(), pt.lsts.asa.settings.Settings.putInt(), pt.lsts.asa.settings.Settings.putString(), pt.lsts.asa.activities.MainActivity.resumeASA(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), pt.lsts.asa.managers.IMCManager.sendToActiveSys(), pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng(), pt.lsts.asa.fragments.GmapFragment.setActiveSysPsi(), pt.lsts.asa.fragments.SystemListFragment.showMoreInfo(), pt.lsts.asa.managers.GPSManager.start(), pt.lsts.asa.comms.Announcer.start(), pt.lsts.asa.activities.MainActivity.test2(), pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker(), pt.lsts.asa.comms.Announcer.updateHeadingOnAnnounce(), and pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce().
static ASA pt.lsts.asa.ASA.getInstance () [static]
Definition at line 192 of file ASA.java.
References pt.lsts.asa.ASA.instance.
LblBeaconList pt.lsts.asa.ASA.getLblBeaconList ()
Definition at line 227 of file ASA.java.
References pt.lsts.asa.ASA.lblBeaconList.
int pt.lsts.asa.ASA.getNextRequestId ()
Returns
the next requestId
Definition at line 275 of file ASA.java.
References pt.lsts.asa.ASA.requestId.
SharedPreferences pt.lsts.asa.ASA.getPrefs ()
Definition at line 262 of file ASA.java.
References pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive(), pt.lsts.asa.managers.GPSManager.start(), pt.lsts.asa.comms.Announcer.start(), pt.lsts.asa.comms.Announcer.updateHeadingOnAnnounce(), and pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce().
SensorManager pt.lsts.asa.ASA.getSensorManager ()
Definition at line 223 of file ASA.java.
References pt.lsts.asa.ASA.sensorManager.
Referenced by pt.lsts.asa.comms.Announcer.start().
SystemList pt.lsts.asa.ASA.getSystemList ()
Definition at line 213 of file ASA.java.
References pt.lsts.asa.ASA.sysList.
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.activities.MainActivity.chooseActiveSystem(), pt.lsts.asa.fragments.SystemListFragment.colorItems(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
void pt.lsts.asa.ASA.initAnnouncer ()
Definition at line 109 of file ASA.java.
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initBroadcast ()
Definition at line 94 of file ASA.java.
References pt.lsts.asa.util.MUtil.getBroadcastAddress().
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initGPSManager (Context context)
Definition at line 113 of file ASA.java.
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initIMCManager ()
Definition at line 124 of file ASA.java.
References pt.lsts.asa.managers.IMCManager.startComms().
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initPreferences (Context context)
Definition at line 119 of file ASA.java.
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initSubscribers (Context context)
Definition at line 129 of file ASA.java.
References pt.lsts.asa.ASA.addInitialSubscribers().
Referenced by pt.lsts.asa.ASA.ASA().
void pt.lsts.asa.ASA.initSystemsList ()
Definition at line 103 of file ASA.java.
Referenced by pt.lsts.asa.ASA.ASA().
boolean pt.lsts.asa.ASA.isStarted ()
Definition at line 267 of file ASA.java.
References pt.lsts.asa.ASA.started.
void pt.lsts.asa.ASA.load ()
Definition at line 146 of file ASA.java.
References pt.lsts.asa.ASA.addLblSubscriber().
Referenced by pt.lsts.asa.App.onCreate().
static void pt.lsts.asa.ASA.notifyMainSysChange () [static], [private]
Definition at line 255 of file ASA.java.
Referenced by pt.lsts.asa.ASA.setActiveSys().
void pt.lsts.asa.ASA.pause ()
Definition at line 170 of file ASA.java.
References pt.lsts.asa.managers.IMCManager.killComms(), pt.lsts.asa.handlers.AccuSmsHandler.stop(), pt.lsts.asa.feedback.Heart.stop(), pt.lsts.asa.comms.Announcer.stop(), and pt.lsts.asa.sys.SystemList.stop().
Referenced by pt.lsts.asa.activities.MainActivity.pauseASA().
void pt.lsts.asa.ASA.removeMainSysChangeListener (MainSysChangeListener listener)
Definition at line 250 of file ASA.java.
void pt.lsts.asa.ASA.setActiveSys (Sys activeS)
Definition at line 202 of file ASA.java.
References pt.lsts.asa.ASA.notifyMainSysChange().
Referenced by pt.lsts.asa.activities.MainActivity.createChooseActiveSystemDialog(), and pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem().
void pt.lsts.asa.ASA.setCallOut (CallOut callOut)
Definition at line 240 of file ASA.java.
References pt.lsts.asa.ASA.callOut.
Referenced by pt.lsts.asa.feedback.CallOut.CallOut().
void pt.lsts.asa.ASA.start ()
Definition at line 157 of file ASA.java.
References pt.lsts.asa.feedback.Heart.start(), pt.lsts.asa.comms.Announcer.start(), pt.lsts.asa.sys.SystemList.start(), and pt.lsts.asa.managers.IMCManager.startComms().
Referenced by pt.lsts.asa.App.onCreate(), and pt.lsts.asa.activities.MainActivity.resumeASA().
Member Data Documentation
AccuSmsHandlerIMCSubscriber pt.lsts.asa.ASA.accuSmsHandlerIMCSubscriber [static]
Definition at line 57 of file ASA.java.
Sys pt.lsts.asa.ASA.activeSys [static], [private]
Definition at line 49 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getActiveSys().
Announcer pt.lsts.asa.ASA.announcer [static]
Definition at line 55 of file ASA.java.
String pt.lsts.asa.ASA.broadcastAddress
Definition at line 68 of file ASA.java.
Bus pt.lsts.asa.ASA.bus [private]
Definition at line 71 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getBus().
CallOut pt.lsts.asa.ASA.callOut [private]
Definition at line 65 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getCallOut(), and pt.lsts.asa.ASA.setCallOut().
Context pt.lsts.asa.ASA.context [static], [private]
Definition at line 47 of file ASA.java.
Referenced by pt.lsts.asa.ASA.ASA(), and pt.lsts.asa.ASA.getContext().
GPSManager pt.lsts.asa.ASA.gpsManager [static]
Definition at line 58 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getGpsManager().
HeartbeatVibrator pt.lsts.asa.ASA.hearbeatVibrator [static]
Definition at line 59 of file ASA.java.
Heart pt.lsts.asa.ASA.heart [static]
Definition at line 61 of file ASA.java.
HeartbeatVibratorIMCSubscriber pt.lsts.asa.ASA.heartbeatVibratorIMCSubscriber [static]
Definition at line 60 of file ASA.java.
IMCManager pt.lsts.asa.ASA.imcManager [static], [private]
Definition at line 51 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getIMCManager().
ASA pt.lsts.asa.ASA.instance [static], [private]
Definition at line 48 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getInstance().
LblBeaconList pt.lsts.asa.ASA.lblBeaconList [static]
Definition at line 62 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getLblBeaconList().
LblBeaconListIMCSubscriber pt.lsts.asa.ASA.lblBeaconListIMCSubscriber [static]
Definition at line 63 of file ASA.java.
ArrayList<MainSysChangeListener> pt.lsts.asa.ASA.mainSysChangeListeners [static], [private]
Definition at line 67 of file ASA.java.
Integer pt.lsts.asa.ASA.requestId = 0xFFFF [static], [private]
Definition at line 73 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getNextRequestId().
SensorManager pt.lsts.asa.ASA.sensorManager [static]
Definition at line 64 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getSensorManager().
SharedPreferences pt.lsts.asa.ASA.sharedPreferences
Definition at line 70 of file ASA.java.
Referenced by pt.lsts.asa.ASA.addPreferencesListenner(), pt.lsts.asa.settings.Settings.clear(), pt.lsts.asa.settings.Settings.exists(), pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.settings.Settings.getBoolean(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.ASA.getPrefs(), pt.lsts.asa.settings.Settings.getSharedPreferences(), pt.lsts.asa.settings.Settings.getString(), pt.lsts.asa.settings.Settings.getStrings(), pt.lsts.asa.settings.Settings.getType(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putFullString(), pt.lsts.asa.settings.Settings.putInt(), and pt.lsts.asa.settings.Settings.putString().
AccuSmsHandler pt.lsts.asa.ASA.smsHandler [static]
Definition at line 56 of file ASA.java.
boolean pt.lsts.asa.ASA.started = false
Definition at line 69 of file ASA.java.
Referenced by pt.lsts.asa.ASA.isStarted(), pt.lsts.asa.activities.MainActivity.pauseASA(), and pt.lsts.asa.activities.MainActivity.resumeASA().
SystemList pt.lsts.asa.ASA.sysList
Definition at line 52 of file ASA.java.
Referenced by pt.lsts.asa.ASA.getSystemList().
SystemListIMCSubscriber pt.lsts.asa.ASA.systemListIMCSubscriber
Definition at line 53 of file ASA.java.
final String pt.lsts.asa.ASA.TAG = `ASA` [static], [private]
Definition at line 43 of file ASA.java.
boolean pt.lsts.asa.ASA.UIThread = false
Definition at line 45 of file ASA.java.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/ASA.java