pt.lsts.asa.fragments.SystemListFragment Class Reference
Public Member Functions
SystemListFragment ()
SystemListFragment (FragmentActivity fragmentActivity)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onResume ()
void onPause ()
void shutdown ()
void setSelectActiveSystemButtonOnClickListener ()
void initScheduler ()
void populateSystemListView ()
String showMoreInfo ()
ArrayList< String > addSysStatus ()
boolean filterSys (Sys sys)
void createListViewAdapter (ArrayList< String > arrayListName)
void setListViewOnItemClickListener ()
void selectActiveSystem ()
void updateListView (final ArrayList< String > arrayListNameFinal)
void colorItems ()
Private Attributes
FragmentActivity fragmentActivity = null
ListView systemListView = null
int selectedInt = -1
Button selectActiveSystemButton = null
String TAG = `SystemListFragment`
ScheduledFuture handle
final ScheduledExecutorService scheduler
Runnable runnable
int interval =100
Detailed Description
Created by jloureiro on 1/5/15.
Definition at line 33 of file SystemListFragment.java.
Constructor & Destructor Documentation
pt.lsts.asa.fragments.SystemListFragment.SystemListFragment ()
Definition at line 49 of file SystemListFragment.java.
pt.lsts.asa.fragments.SystemListFragment.SystemListFragment (FragmentActivity fragmentActivity)
Definition at line 53 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.fragmentActivity.
Member Function Documentation
ArrayList<String> pt.lsts.asa.fragments.SystemListFragment.addSysStatus ()
Definition at line 145 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.filterSys(), pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.SystemList.getList(), pt.lsts.asa.sys.SystemList.getNameList(), pt.lsts.asa.ASA.getSystemList(), pt.lsts.asa.sys.Sys.getType(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
Referenced by pt.lsts.asa.fragments.SystemListFragment.populateSystemListView().
void pt.lsts.asa.fragments.SystemListFragment.colorItems ()
Definition at line 242 of file SystemListFragment.java.
References pt.lsts.asa.sys.SystemList.findSysByName(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.SystemList.getList(), pt.lsts.asa.ASA.getSystemList(), pt.lsts.asa.sys.Sys.getType(), pt.lsts.asa.sys.Sys.isConnected(), pt.lsts.asa.sys.Sys.isError(), and pt.lsts.asa.util.StringUtils.removeSysExtraInfo().
Referenced by pt.lsts.asa.fragments.SystemListFragment.createListViewAdapter(), and pt.lsts.asa.fragments.SystemListFragment.updateListView().
void pt.lsts.asa.fragments.SystemListFragment.createListViewAdapter (ArrayList< String > arrayListName)
Definition at line 188 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.colorItems(), and pt.lsts.asa.fragments.SystemListFragment.fragmentActivity.
Referenced by pt.lsts.asa.fragments.SystemListFragment.populateSystemListView().
boolean pt.lsts.asa.fragments.SystemListFragment.filterSys (Sys sys)
Definition at line 174 of file SystemListFragment.java.
References pt.lsts.asa.settings.Settings.getBoolean(), and pt.lsts.asa.sys.Sys.getType().
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus().
void pt.lsts.asa.fragments.SystemListFragment.initScheduler ()
Definition at line 93 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.populateSystemListView().
Referenced by pt.lsts.asa.fragments.SystemListFragment.onResume().
View pt.lsts.asa.fragments.SystemListFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 58 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.setSelectActiveSystemButtonOnClickListener().
void pt.lsts.asa.fragments.SystemListFragment.onPause ()
Definition at line 74 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.shutdown().
void pt.lsts.asa.fragments.SystemListFragment.onResume ()
Definition at line 67 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.initScheduler().
void pt.lsts.asa.fragments.SystemListFragment.populateSystemListView ()
Definition at line 106 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.fragments.SystemListFragment.createListViewAdapter(), pt.lsts.asa.fragments.SystemListFragment.setListViewOnItemClickListener(), and pt.lsts.asa.fragments.SystemListFragment.updateListView().
Referenced by pt.lsts.asa.fragments.SystemListFragment.initScheduler(), and pt.lsts.asa.activities.SystemListActivity.onOptionsItemSelected().
void pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem ()
Definition at line 214 of file SystemListFragment.java.
References pt.lsts.asa.sys.SystemList.findSysByName(), pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getName(), pt.lsts.asa.ASA.getSystemList(), pt.lsts.asa.util.StringUtils.removeSysExtraInfo(), pt.lsts.asa.ASA.setActiveSys(), and pt.lsts.asa.util.AndroidUtil.showToastLong().
Referenced by pt.lsts.asa.activities.SystemListActivity.onOptionsItemSelected(), and pt.lsts.asa.fragments.SystemListFragment.setSelectActiveSystemButtonOnClickListener().
void pt.lsts.asa.fragments.SystemListFragment.setListViewOnItemClickListener ()
Definition at line 197 of file SystemListFragment.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.populateSystemListView().
void pt.lsts.asa.fragments.SystemListFragment.setSelectActiveSystemButtonOnClickListener ()
Definition at line 84 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem().
Referenced by pt.lsts.asa.fragments.SystemListFragment.onCreateView().
String pt.lsts.asa.fragments.SystemListFragment.showMoreInfo ()
Definition at line 118 of file SystemListFragment.java.
References pt.lsts.asa.sys.SystemList.findSysByName(), pt.lsts.asa.sys.Sys.getAddress(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.ASA.getSystemList(), pt.lsts.asa.sys.Sys.isConnected(), pt.lsts.asa.sys.Sys.isError(), pt.lsts.asa.sys.Sys.lastMessageReceived, pt.lsts.asa.util.StringUtils.removeSysExtraInfo(), pt.lsts.asa.util.AndroidUtil.showToastLong(), and pt.lsts.asa.util.StringUtils.timeSinceLastMessage().
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), and pt.lsts.asa.activities.SystemListActivity.onOptionsItemSelected().
void pt.lsts.asa.fragments.SystemListFragment.shutdown ()
Definition at line 79 of file SystemListFragment.java.
Referenced by pt.lsts.asa.activities.SystemListActivity.onBackPressed(), and pt.lsts.asa.fragments.SystemListFragment.onPause().
void pt.lsts.asa.fragments.SystemListFragment.updateListView (final ArrayList< String > arrayListNameFinal)
Definition at line 231 of file SystemListFragment.java.
References pt.lsts.asa.fragments.SystemListFragment.colorItems().
Referenced by pt.lsts.asa.fragments.SystemListFragment.populateSystemListView().
Member Data Documentation
FragmentActivity pt.lsts.asa.fragments.SystemListFragment.fragmentActivity = null [private]
Definition at line 35 of file SystemListFragment.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.createListViewAdapter(), and pt.lsts.asa.fragments.SystemListFragment.SystemListFragment().
ScheduledFuture pt.lsts.asa.fragments.SystemListFragment.handle [private]
Definition at line 41 of file SystemListFragment.java.
int pt.lsts.asa.fragments.SystemListFragment.interval =100 [private]
Definition at line 45 of file SystemListFragment.java.
Runnable pt.lsts.asa.fragments.SystemListFragment.runnable [private]
Definition at line 44 of file SystemListFragment.java.
final ScheduledExecutorService pt.lsts.asa.fragments.SystemListFragment.scheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 42 of file SystemListFragment.java.
Button pt.lsts.asa.fragments.SystemListFragment.selectActiveSystemButton = null [private]
Definition at line 38 of file SystemListFragment.java.
int pt.lsts.asa.fragments.SystemListFragment.selectedInt = -1 [private]
Definition at line 37 of file SystemListFragment.java.
ListView pt.lsts.asa.fragments.SystemListFragment.systemListView = null [private]
Definition at line 36 of file SystemListFragment.java.
String pt.lsts.asa.fragments.SystemListFragment.TAG = `SystemListFragment` [private]
Definition at line 39 of file SystemListFragment.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/fragments/SystemListFragment.java