pt.lsts.asa.fragments.ManualIndicatorsFragment Class Reference
Public Member Functions
ManualIndicatorsFragment ()
ManualIndicatorsFragment (FragmentActivity fragmentActivity)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void init ()
void initPreferencesListenner ()
void initIMCSubscriber ()
void findViews (View v)
void setTextViewsColors ()
void setBackgroundColors ()
void setTextColors ()
void onResume ()
void setLeftTextView (final String text)
void setRightTextView (final String text)
void setInterval (int interval)
void setCenterTextViewVisibility (final boolean visibility)
void setRunnalbe ()
void startScheduler (Boolean visibility)
Private Attributes
FragmentActivity fragmentActivity = null
TextView leftTextView = null
TextView rightTextView = null
TextView centerTextView = null
ManualIndicatorsFragmentIMCSubscriber manualIndicatorsFragmentIMCSubscriber = null
ScheduledFuture handle
final ScheduledExecutorService scheduler
Runnable runnable
int interval = (Settings.getInt(`timeout_interval_in_seconds`, 60) * 1000)
Detailed Description
Created by jloureiro on 1/14/15.
Definition at line 26 of file ManualIndicatorsFragment.java.
Constructor & Destructor Documentation
pt.lsts.asa.fragments.ManualIndicatorsFragment.ManualIndicatorsFragment ()
Definition at line 39 of file ManualIndicatorsFragment.java.
pt.lsts.asa.fragments.ManualIndicatorsFragment.ManualIndicatorsFragment (FragmentActivity fragmentActivity)
Definition at line 43 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.fragmentActivity.
Member Function Documentation
void pt.lsts.asa.fragments.ManualIndicatorsFragment.findViews (View v)
Definition at line 75 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.onCreateView().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.init ()
Definition at line 58 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.initIMCSubscriber(), pt.lsts.asa.fragments.ManualIndicatorsFragment.initPreferencesListenner(), pt.lsts.asa.fragments.ManualIndicatorsFragment.setRunnalbe(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.startScheduler().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.onCreateView().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.initIMCSubscriber ()
Definition at line 70 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.ASA.addSubscriber(), and pt.lsts.asa.ASA.getInstance().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.init().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.initPreferencesListenner ()
Definition at line 65 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.ASA.getBus(), and pt.lsts.asa.ASA.getInstance().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.init().
View pt.lsts.asa.fragments.ManualIndicatorsFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 48 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.findViews(), pt.lsts.asa.fragments.ManualIndicatorsFragment.init(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextViewsColors().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.onResume ()
Definition at line 99 of file ManualIndicatorsFragment.java.
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setBackgroundColors ()
Definition at line 86 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextViewsColors().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setCenterTextViewVisibility (final boolean visibility)
Definition at line 127 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.setLeftTextView(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setRightTextView().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.setRunnalbe(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.startScheduler().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setInterval (int interval)
Definition at line 122 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.interval, and pt.lsts.asa.fragments.ManualIndicatorsFragment.startScheduler().
Referenced by pt.lsts.asa.listenners.sharedPreferences.ManualIndicatorsPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setLeftTextView (final String text)
Definition at line 104 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.onReceive(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setCenterTextViewVisibility().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setRightTextView (final String text)
Definition at line 113 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.onReceive(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setCenterTextViewVisibility().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setRunnalbe ()
Definition at line 143 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.setCenterTextViewVisibility().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.init().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextColors ()
Definition at line 92 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextViewsColors().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextViewsColors ()
Definition at line 81 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.setBackgroundColors(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setTextColors().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.onCreateView().
void pt.lsts.asa.fragments.ManualIndicatorsFragment.startScheduler (Boolean visibility)
Definition at line 152 of file ManualIndicatorsFragment.java.
References pt.lsts.asa.fragments.ManualIndicatorsFragment.setCenterTextViewVisibility().
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.init(), pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.onReceive(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.setInterval().
Member Data Documentation
TextView pt.lsts.asa.fragments.ManualIndicatorsFragment.centerTextView = null [private]
Definition at line 31 of file ManualIndicatorsFragment.java.
FragmentActivity pt.lsts.asa.fragments.ManualIndicatorsFragment.fragmentActivity = null [private]
Definition at line 28 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.ManualIndicatorsFragment().
ScheduledFuture pt.lsts.asa.fragments.ManualIndicatorsFragment.handle [private]
Definition at line 33 of file ManualIndicatorsFragment.java.
int pt.lsts.asa.fragments.ManualIndicatorsFragment.interval = (Settings.getInt(`timeout_interval_in_seconds`, 60) * 1000) [private]
Definition at line 37 of file ManualIndicatorsFragment.java.
Referenced by pt.lsts.asa.fragments.ManualIndicatorsFragment.setInterval().
TextView pt.lsts.asa.fragments.ManualIndicatorsFragment.leftTextView = null [private]
Definition at line 29 of file ManualIndicatorsFragment.java.
ManualIndicatorsFragmentIMCSubscriber pt.lsts.asa.fragments.ManualIndicatorsFragment.manualIndicatorsFragmentIMCSubscriber = null [private]
Definition at line 32 of file ManualIndicatorsFragment.java.
TextView pt.lsts.asa.fragments.ManualIndicatorsFragment.rightTextView = null [private]
Definition at line 30 of file ManualIndicatorsFragment.java.
Runnable pt.lsts.asa.fragments.ManualIndicatorsFragment.runnable [private]
Definition at line 36 of file ManualIndicatorsFragment.java.
final ScheduledExecutorService pt.lsts.asa.fragments.ManualIndicatorsFragment.scheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 34 of file ManualIndicatorsFragment.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/fragments/ManualIndicatorsFragment.java