pt.lsts.asa.subscribers.GmapIMCSubscriber Class Reference
Public Member Functions
GmapIMCSubscriber (GmapFragment gmapFragment)
void onReceive (final IMCMessage msg)
LatLng translateCoordinates (final LatLng origpoint, final float offsetX, final float offsetY)
Private Attributes
final String TAG = `GmapIMCSubscriber`
GmapFragment gmapfragment = null
Thread thread
float r_earth = 6378 * 1000
Detailed Description
Created by jloureiro on 1/22/15.
Definition at line 18 of file GmapIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.GmapIMCSubscriber.GmapIMCSubscriber (GmapFragment gmapFragment)
Definition at line 25 of file GmapIMCSubscriber.java.
Member Function Documentation
void pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 30 of file GmapIMCSubscriber.java.
References pt.lsts.asa.fragments.GmapFragment.getGoogleMap(), pt.lsts.asa.util.IMCUtils.isMsgFromActive(), pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng(), pt.lsts.asa.fragments.GmapFragment.setActiveSysPsi(), pt.lsts.asa.subscribers.GmapIMCSubscriber.translateCoordinates(), and pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
LatLng pt.lsts.asa.subscribers.GmapIMCSubscriber.translateCoordinates (final LatLng origpoint, final float offsetX, final float offsetY)
Definition at line 69 of file GmapIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive().
Member Data Documentation
GmapFragment pt.lsts.asa.subscribers.GmapIMCSubscriber.gmapfragment = null [private]
Definition at line 21 of file GmapIMCSubscriber.java.
float pt.lsts.asa.subscribers.GmapIMCSubscriber.r_earth = 6378 * 1000 [private]
Definition at line 23 of file GmapIMCSubscriber.java.
final String pt.lsts.asa.subscribers.GmapIMCSubscriber.TAG = `GmapIMCSubscriber` [private]
Definition at line 20 of file GmapIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.GmapIMCSubscriber.thread [private]
Definition at line 22 of file GmapIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/GmapIMCSubscriber.java