pt.lsts.asa.activities.ManualActivity Class Reference
Public Member Functions
void loadFragments (Bundle savedInstanceState)
void onBackPressed ()
void back ()
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onPostCreate (Bundle savedInstanceState)
Private Attributes
SoundControlFragment soundControlFragment = null
VideoViewFragment videoViewFragment = null
SettingsButtonFragment settingsButtonFragment = null
ManualIndicatorsFragment manualIndicatorsFragment = null
CallOut callOut
Detailed Description
Definition at line 18 of file ManualActivity.java.
Member Function Documentation
void pt.lsts.asa.activities.ManualActivity.back ()
Definition at line 77 of file ManualActivity.java.
References pt.lsts.asa.feedback.CallOut.shutdown(), and pt.lsts.asa.fragments.SoundControlFragment.shutdown().
Referenced by pt.lsts.asa.activities.ManualActivity.onBackPressed().
void pt.lsts.asa.activities.ManualActivity.loadFragments (Bundle savedInstanceState)
Definition at line 37 of file ManualActivity.java.
References pt.lsts.asa.util.AndroidUtil.loadFragment().
Referenced by pt.lsts.asa.activities.ManualActivity.onCreate().
void pt.lsts.asa.activities.ManualActivity.onBackPressed ()
Definition at line 65 of file ManualActivity.java.
References pt.lsts.asa.activities.ManualActivity.back().
void pt.lsts.asa.activities.ManualActivity.onCreate (Bundle savedInstanceState) [protected]
Definition at line 27 of file ManualActivity.java.
References pt.lsts.asa.ASA.getContext(), pt.lsts.asa.feedback.CallOut.initCallOuts(), and pt.lsts.asa.activities.ManualActivity.loadFragments().
void pt.lsts.asa.activities.ManualActivity.onPostCreate (Bundle savedInstanceState) [protected]
Definition at line 59 of file ManualActivity.java.
References pt.lsts.asa.fragments.SoundControlFragment.unmute().
Member Data Documentation
CallOut pt.lsts.asa.activities.ManualActivity.callOut [private]
Definition at line 24 of file ManualActivity.java.
ManualIndicatorsFragment pt.lsts.asa.activities.ManualActivity.manualIndicatorsFragment = null [private]
Definition at line 23 of file ManualActivity.java.
SettingsButtonFragment pt.lsts.asa.activities.ManualActivity.settingsButtonFragment = null [private]
Definition at line 22 of file ManualActivity.java.
SoundControlFragment pt.lsts.asa.activities.ManualActivity.soundControlFragment = null [private]
Definition at line 20 of file ManualActivity.java.
VideoViewFragment pt.lsts.asa.activities.ManualActivity.videoViewFragment = null [private]
Definition at line 21 of file ManualActivity.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/activities/ManualActivity.java