pt.lsts.asa.pos.UTMCoordinates Class Reference
Public Member Functions
UTMCoordinates (double easting, double northing, int zone_number, char zone_letter)
UTMCoordinates (double latitude, double longitude)
void UTMtoLL ()
void LLtoUTM ()
double getEasting ()
void setEasting (double easting)
double getNorthing ()
void setNorthing (double northing)
char getZone_letter ()
int getZone_number ()
double getLatitude ()
void setLatitude (double latitude)
double getLongitude ()
void setLongitude (double longitude)
Private Attributes
final double WGS84_radius = 6378137.0d
final double WGS84_eccSqared = 0.00669438d
double easting = 0.0
double northing = 0.0
double latitude = 0.0
double longitude = 0.0
int zone_number = 0
char zone_letter = 'T'
Detailed Description
Author
ZP
Definition at line 22 of file UTMCoordinates.java.
Constructor & Destructor Documentation
pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates (double easting, double northing, int zone_number, char zone_letter)
Definition at line 35 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.easting, pt.lsts.asa.pos.UTMCoordinates.northing, pt.lsts.asa.pos.UTMCoordinates.UTMtoLL(), pt.lsts.asa.pos.UTMCoordinates.zone_letter, and pt.lsts.asa.pos.UTMCoordinates.zone_number.
pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates (double latitude, double longitude)
Definition at line 44 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.latitude, pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), and pt.lsts.asa.pos.UTMCoordinates.longitude.
Member Function Documentation
double pt.lsts.asa.pos.UTMCoordinates.getEasting ()
Definition at line 225 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.easting.
Referenced by pt.lsts.asa.util.CoordUtil.latLonDiff().
double pt.lsts.asa.pos.UTMCoordinates.getLatitude ()
Definition at line 251 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.latitude.
double pt.lsts.asa.pos.UTMCoordinates.getLongitude ()
Definition at line 260 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.longitude.
double pt.lsts.asa.pos.UTMCoordinates.getNorthing ()
Definition at line 234 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.northing.
Referenced by pt.lsts.asa.util.CoordUtil.latLonDiff().
char pt.lsts.asa.pos.UTMCoordinates.getZone_letter ()
Definition at line 243 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.zone_letter.
int pt.lsts.asa.pos.UTMCoordinates.getZone_number ()
Definition at line 247 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.zone_number.
void pt.lsts.asa.pos.UTMCoordinates.LLtoUTM ()
Definition at line 130 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.latitude, pt.lsts.asa.pos.UTMCoordinates.longitude, pt.lsts.asa.pos.UTMCoordinates.WGS84_eccSqared, and pt.lsts.asa.pos.UTMCoordinates.WGS84_radius.
Referenced by pt.lsts.asa.pos.UTMCoordinates.setLatitude(), pt.lsts.asa.pos.UTMCoordinates.setLongitude(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
void pt.lsts.asa.pos.UTMCoordinates.setEasting (double easting)
Definition at line 229 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.easting, and pt.lsts.asa.pos.UTMCoordinates.UTMtoLL().
void pt.lsts.asa.pos.UTMCoordinates.setLatitude (double latitude)
Definition at line 255 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.latitude, and pt.lsts.asa.pos.UTMCoordinates.LLtoUTM().
void pt.lsts.asa.pos.UTMCoordinates.setLongitude (double longitude)
Definition at line 264 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), and pt.lsts.asa.pos.UTMCoordinates.longitude.
void pt.lsts.asa.pos.UTMCoordinates.setNorthing (double northing)
Definition at line 238 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.northing, and pt.lsts.asa.pos.UTMCoordinates.UTMtoLL().
void pt.lsts.asa.pos.UTMCoordinates.UTMtoLL ()
Definition at line 52 of file UTMCoordinates.java.
References pt.lsts.asa.pos.UTMCoordinates.northing, pt.lsts.asa.pos.UTMCoordinates.WGS84_eccSqared, and pt.lsts.asa.pos.UTMCoordinates.WGS84_radius.
Referenced by pt.lsts.asa.pos.UTMCoordinates.setEasting(), pt.lsts.asa.pos.UTMCoordinates.setNorthing(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
Member Data Documentation
double pt.lsts.asa.pos.UTMCoordinates.easting = 0.0 [private]
Definition at line 26 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getEasting(), pt.lsts.asa.pos.UTMCoordinates.setEasting(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
double pt.lsts.asa.pos.UTMCoordinates.latitude = 0.0 [private]
Definition at line 29 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getLatitude(), pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), pt.lsts.asa.pos.UTMCoordinates.setLatitude(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
double pt.lsts.asa.pos.UTMCoordinates.longitude = 0.0 [private]
Definition at line 30 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getLongitude(), pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), pt.lsts.asa.pos.UTMCoordinates.setLongitude(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
double pt.lsts.asa.pos.UTMCoordinates.northing = 0.0 [private]
Definition at line 27 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getNorthing(), pt.lsts.asa.pos.UTMCoordinates.setNorthing(), pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates(), and pt.lsts.asa.pos.UTMCoordinates.UTMtoLL().
final double pt.lsts.asa.pos.UTMCoordinates.WGS84_eccSqared = 0.00669438d [private]
Definition at line 24 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), and pt.lsts.asa.pos.UTMCoordinates.UTMtoLL().
final double pt.lsts.asa.pos.UTMCoordinates.WGS84_radius = 6378137.0d [private]
Definition at line 23 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.LLtoUTM(), and pt.lsts.asa.pos.UTMCoordinates.UTMtoLL().
char pt.lsts.asa.pos.UTMCoordinates.zone_letter = 'T' [private]
Definition at line 33 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getZone_letter(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
int pt.lsts.asa.pos.UTMCoordinates.zone_number = 0 [private]
Definition at line 32 of file UTMCoordinates.java.
Referenced by pt.lsts.asa.pos.UTMCoordinates.getZone_number(), and pt.lsts.asa.pos.UTMCoordinates.UTMCoordinates().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/pos/UTMCoordinates.java