pt.lsts.asa.activities.AutoActivity Class Reference
Public Member Functions
void loadFragments (Bundle savedInstanceState)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Detailed Description
Definition at line 11 of file AutoActivity.java.
Member Function Documentation
void pt.lsts.asa.activities.AutoActivity.loadFragments (Bundle savedInstanceState)
Definition at line 24 of file AutoActivity.java.
References pt.lsts.asa.util.AndroidUtil.loadFragment().
Referenced by pt.lsts.asa.activities.AutoActivity.onCreate().
void pt.lsts.asa.activities.AutoActivity.onCreate (Bundle savedInstanceState) [protected]
Definition at line 16 of file AutoActivity.java.
References pt.lsts.asa.activities.AutoActivity.loadFragments().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/activities/AutoActivity.java