pt.lsts.asa.App Class Reference
Public Member Functions
void onCreate ()
void initSettings ()
Static Public Member Functions
static AudioManager getAudioManager ()
Static Private Attributes
static AudioManager audioManager
Detailed Description
Class extending application that does a single startup for the application needed to initialize ACCU state object
Author
sharp
Definition at line 20 of file App.java.
Member Function Documentation
static AudioManager pt.lsts.asa.App.getAudioManager () [static]
Definition at line 24 of file App.java.
References pt.lsts.asa.App.audioManager.
Referenced by pt.lsts.asa.managers.SoundManager.SoundManager().
void pt.lsts.asa.App.initSettings ()
Definition at line 44 of file App.java.
References pt.lsts.asa.util.FileOperations.copySpecificAsset(), pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.settings.Settings.getSettings(), and pt.lsts.asa.settings.Profile.restoreDefaults().
Referenced by pt.lsts.asa.App.onCreate().
void pt.lsts.asa.App.onCreate ()
Definition at line 29 of file App.java.
References pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.App.initSettings(), pt.lsts.asa.ASA.load(), and pt.lsts.asa.ASA.start().
Member Data Documentation
AudioManager pt.lsts.asa.App.audioManager [static], [private]
Definition at line 22 of file App.java.
Referenced by pt.lsts.asa.App.getAudioManager().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/App.java