pt.lsts.asa.pos.Beacon Class Reference
Public Member Functions
Beacon (String name, double lat, double lon, double depth)
String getName ()
double getLat ()
void setLat (double lat)
double getLon ()
void setLon (double lon)
double getDepth ()
void setDepth (double depth)
int getInterrogationChannel ()
void setInterrogationChannel (int interrogationChannel)
int getReplayChannel ()
void setReplyChannel (int replayChannel)
int getTransponderDelay ()
void setTransponderDelay (int transponderDelay)
String getLatDMS ()
String getLonDMS ()
String toString ()
Detailed Description
Definition at line 5 of file Beacon.java.
Constructor & Destructor Documentation
pt.lsts.asa.pos.Beacon.Beacon (String name, double lat, double lon, double depth)
Definition at line 15 of file Beacon.java.
Member Function Documentation
double pt.lsts.asa.pos.Beacon.getDepth ()
Definition at line 43 of file Beacon.java.
int pt.lsts.asa.pos.Beacon.getInterrogationChannel ()
Definition at line 51 of file Beacon.java.
double pt.lsts.asa.pos.Beacon.getLat ()
Definition at line 27 of file Beacon.java.
String pt.lsts.asa.pos.Beacon.getLatDMS ()
Definition at line 75 of file Beacon.java.
References pt.lsts.asa.util.CoordUtil.degreesToDMS().
double pt.lsts.asa.pos.Beacon.getLon ()
Definition at line 35 of file Beacon.java.
String pt.lsts.asa.pos.Beacon.getLonDMS ()
Definition at line 79 of file Beacon.java.
References pt.lsts.asa.util.CoordUtil.degreesToDMS().
String pt.lsts.asa.pos.Beacon.getName ()
Definition at line 23 of file Beacon.java.
int pt.lsts.asa.pos.Beacon.getReplayChannel ()
Definition at line 59 of file Beacon.java.
int pt.lsts.asa.pos.Beacon.getTransponderDelay ()
Definition at line 67 of file Beacon.java.
void pt.lsts.asa.pos.Beacon.setDepth (double depth)
Definition at line 47 of file Beacon.java.
void pt.lsts.asa.pos.Beacon.setInterrogationChannel (int interrogationChannel)
Definition at line 55 of file Beacon.java.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive().
void pt.lsts.asa.pos.Beacon.setLat (double lat)
Definition at line 31 of file Beacon.java.
void pt.lsts.asa.pos.Beacon.setLon (double lon)
Definition at line 39 of file Beacon.java.
void pt.lsts.asa.pos.Beacon.setReplyChannel (int replayChannel)
Definition at line 63 of file Beacon.java.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive().
void pt.lsts.asa.pos.Beacon.setTransponderDelay (int transponderDelay)
Definition at line 71 of file Beacon.java.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive().
String pt.lsts.asa.pos.Beacon.toString ()
Definition at line 84 of file Beacon.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/pos/Beacon.java