pt.lsts.asa.feedback.CallOut Class Reference
Public Member Functions
CallOut (Context context)
void initImcSubscribers ()
void initSchedulers ()
void shutdown ()
void initCallOuts ()
void initTextToSpeech ()
void initBooleans ()
void initIntervals ()
void startCallOuts ()
void shutdownCallOuts ()
void shutdownHandlers ()
void shutdownSchedulers ()
void initAltRunnale ()
void startAltHandle ()
void initIasRunnable ()
void startIasHandle ()
boolean isTimeout ()
void initTimeoutRunnable ()
void startTimeoutHandle ()
void setIasValue (Double iasValue)
void setAltValue (Float altValue)
void setSpeechRate (int speechRate)
void setLastMsgReceived (long lastMsgReceived)
void setTimeoutBool (boolean timeoutBool)
void setIasInterval (int iasInterval)
void setAltInterval (int altInterval)
void setTimeoutInterval (int timeoutInterval)
void setIasMuteBool (boolean iasBool)
void setAltMuteBool (boolean altBool)
void setGlobalMuteBool (boolean globalAudioBool)
Private Attributes
final String TAG = `CallOut`
TextToSpeech tts
Context context
CallOutIMCSubscriber callOutIMCSubscriber
ScheduledFuture iasHandle
ScheduledExecutorService iasScheduler
ScheduledExecutorService altScheduler
ScheduledExecutorService timeoutScheduler
Float altValue = 0f
Double iasValue = 0d
long lastMsgReceived = 0
int iasInterval = 10000
boolean iasMuteBool = false
Detailed Description
Text to Speech
Author
Definition at line 28 of file CallOut.java.
Constructor & Destructor Documentation
pt.lsts.asa.feedback.CallOut.CallOut (Context context)
Definition at line 52 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.context, pt.lsts.asa.ASA.getBus(), pt.lsts.asa.managers.SoundManager.getInstance(), pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.setCallOut().
Member Function Documentation
void pt.lsts.asa.feedback.CallOut.initAltRunnale ()
Definition at line 144 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.isTimeout(), and pt.lsts.asa.feedback.CallOut.startAltHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initBooleans ()
Definition at line 99 of file CallOut.java.
References pt.lsts.asa.settings.Settings.getBoolean().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initCallOuts ()
Definition at line 77 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.initAltRunnale(), pt.lsts.asa.feedback.CallOut.initBooleans(), pt.lsts.asa.feedback.CallOut.initIasRunnable(), pt.lsts.asa.feedback.CallOut.initImcSubscribers(), pt.lsts.asa.feedback.CallOut.initIntervals(), pt.lsts.asa.feedback.CallOut.initSchedulers(), pt.lsts.asa.feedback.CallOut.initTextToSpeech(), and pt.lsts.asa.feedback.CallOut.initTimeoutRunnable().
Referenced by pt.lsts.asa.activities.ManualActivity.onCreate().
void pt.lsts.asa.feedback.CallOut.initIasRunnable ()
Definition at line 174 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.isTimeout(), and pt.lsts.asa.feedback.CallOut.startIasHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initImcSubscribers ()
Definition at line 61 of file CallOut.java.
References pt.lsts.asa.ASA.addSubscriber(), and pt.lsts.asa.ASA.getInstance().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initIntervals ()
Definition at line 106 of file CallOut.java.
References pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.feedback.CallOut.setAltInterval(), pt.lsts.asa.feedback.CallOut.setIasInterval(), and pt.lsts.asa.feedback.CallOut.setTimeoutInterval().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initSchedulers ()
Definition at line 66 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts(), and pt.lsts.asa.feedback.CallOut.startCallOuts().
void pt.lsts.asa.feedback.CallOut.initTextToSpeech ()
Definition at line 88 of file CallOut.java.
References pt.lsts.asa.settings.Settings.getInt(), and pt.lsts.asa.feedback.CallOut.setSpeechRate().
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
void pt.lsts.asa.feedback.CallOut.initTimeoutRunnable ()
Definition at line 215 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.lastMsgReceived.
Referenced by pt.lsts.asa.feedback.CallOut.initCallOuts().
boolean pt.lsts.asa.feedback.CallOut.isTimeout ()
Definition at line 206 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.lastMsgReceived, pt.lsts.asa.feedback.CallOut.setTimeoutBool(), and pt.lsts.asa.feedback.CallOut.startTimeoutHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initAltRunnale(), pt.lsts.asa.feedback.CallOut.initIasRunnable(), and pt.lsts.asa.feedback.CallOut.setTimeoutBool().
void pt.lsts.asa.feedback.CallOut.setAltInterval (int altInterval)
Definition at line 272 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.startAltHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initIntervals(), and pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setAltMuteBool (boolean altBool)
Definition at line 287 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.startAltHandle().
Referenced by pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setAltValue (Float altValue)
Definition at line 249 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.altValue.
Referenced by pt.lsts.asa.subscribers.CallOutIMCSubscriber.onReceive().
void pt.lsts.asa.feedback.CallOut.setGlobalMuteBool (boolean globalAudioBool)
Definition at line 292 of file CallOut.java.
Referenced by pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setIasInterval (int iasInterval)
Definition at line 267 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.iasInterval, and pt.lsts.asa.feedback.CallOut.startIasHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initIntervals(), and pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setIasMuteBool (boolean iasBool)
Definition at line 282 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.startIasHandle().
Referenced by pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setIasValue (Double iasValue)
Definition at line 245 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.iasValue.
Referenced by pt.lsts.asa.subscribers.CallOutIMCSubscriber.onReceive().
void pt.lsts.asa.feedback.CallOut.setLastMsgReceived (long lastMsgReceived)
Definition at line 257 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.lastMsgReceived, and pt.lsts.asa.feedback.CallOut.setTimeoutBool().
Referenced by pt.lsts.asa.subscribers.CallOutIMCSubscriber.onReceive().
void pt.lsts.asa.feedback.CallOut.setSpeechRate (int speechRate)
Definition at line 253 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.initTextToSpeech(), and pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.setTimeoutBool (boolean timeoutBool)
Definition at line 262 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.isTimeout().
Referenced by pt.lsts.asa.feedback.CallOut.isTimeout(), pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged(), and pt.lsts.asa.feedback.CallOut.setLastMsgReceived().
void pt.lsts.asa.feedback.CallOut.setTimeoutInterval (int timeoutInterval)
Definition at line 277 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.startTimeoutHandle().
Referenced by pt.lsts.asa.feedback.CallOut.initIntervals(), and pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged().
void pt.lsts.asa.feedback.CallOut.shutdown ()
Definition at line 72 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.shutdownCallOuts().
Referenced by pt.lsts.asa.activities.ManualActivity.back().
void pt.lsts.asa.feedback.CallOut.shutdownCallOuts ()
Definition at line 121 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.shutdownHandlers(), and pt.lsts.asa.feedback.CallOut.shutdownSchedulers().
Referenced by pt.lsts.asa.feedback.CallOut.shutdown().
void pt.lsts.asa.feedback.CallOut.shutdownHandlers ()
Definition at line 126 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.shutdownCallOuts().
void pt.lsts.asa.feedback.CallOut.shutdownSchedulers ()
Definition at line 135 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.shutdownCallOuts().
void pt.lsts.asa.feedback.CallOut.startAltHandle ()
Definition at line 166 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.initAltRunnale(), pt.lsts.asa.feedback.CallOut.setAltInterval(), pt.lsts.asa.feedback.CallOut.setAltMuteBool(), and pt.lsts.asa.feedback.CallOut.startCallOuts().
void pt.lsts.asa.feedback.CallOut.startCallOuts ()
Definition at line 115 of file CallOut.java.
References pt.lsts.asa.feedback.CallOut.initSchedulers(), pt.lsts.asa.feedback.CallOut.startAltHandle(), and pt.lsts.asa.feedback.CallOut.startIasHandle().
void pt.lsts.asa.feedback.CallOut.startIasHandle ()
Definition at line 198 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.initIasRunnable(), pt.lsts.asa.feedback.CallOut.setIasInterval(), pt.lsts.asa.feedback.CallOut.setIasMuteBool(), and pt.lsts.asa.feedback.CallOut.startCallOuts().
void pt.lsts.asa.feedback.CallOut.startTimeoutHandle ()
Definition at line 237 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.isTimeout(), and pt.lsts.asa.feedback.CallOut.setTimeoutInterval().
Member Data Documentation
ScheduledExecutorService pt.lsts.asa.feedback.CallOut.altScheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 38 of file CallOut.java.
Float pt.lsts.asa.feedback.CallOut.altValue = 0f [private]
Definition at line 44 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.setAltValue().
CallOutIMCSubscriber pt.lsts.asa.feedback.CallOut.callOutIMCSubscriber [private]
Definition at line 33 of file CallOut.java.
Context pt.lsts.asa.feedback.CallOut.context [private]
Definition at line 32 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.CallOut().
ScheduledFuture pt.lsts.asa.feedback.CallOut.iasHandle [private]
Definition at line 35 of file CallOut.java.
int pt.lsts.asa.feedback.CallOut.iasInterval = 10000 [private]
Definition at line 49 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.setIasInterval().
boolean pt.lsts.asa.feedback.CallOut.iasMuteBool = false [private]
Definition at line 50 of file CallOut.java.
ScheduledExecutorService pt.lsts.asa.feedback.CallOut.iasScheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 36 of file CallOut.java.
Double pt.lsts.asa.feedback.CallOut.iasValue = 0d [private]
Definition at line 45 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.setIasValue().
long pt.lsts.asa.feedback.CallOut.lastMsgReceived = 0 [private]
Definition at line 47 of file CallOut.java.
Referenced by pt.lsts.asa.feedback.CallOut.initTimeoutRunnable(), pt.lsts.asa.feedback.CallOut.isTimeout(), and pt.lsts.asa.feedback.CallOut.setLastMsgReceived().
final String pt.lsts.asa.feedback.CallOut.TAG = `CallOut` [private]
Definition at line 30 of file CallOut.java.
ScheduledExecutorService pt.lsts.asa.feedback.CallOut.timeoutScheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 40 of file CallOut.java.
TextToSpeech pt.lsts.asa.feedback.CallOut.tts [private]
Definition at line 31 of file CallOut.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/feedback/CallOut.java