pt.lsts.asa.activities.MainActivity Class Reference
Public Member Functions
void setSystemListButton ()
void test ()
void test2 ()
void setChooseActiveSystemButton (final Context context)
void chooseActiveSystem (Context context)
void createChooseActiveSystemDialog (Context context, String[] array, final ArrayList< Sys > arrayListSys)
void setTestButton ()
void setTest2Button ()
void setSettingsCheckListButton ()
void setManualButton ()
void setAutoButton ()
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void onPause ()
void onResume ()
void onBackPressed ()
void back ()
void pauseASA ()
void resumeASA ()
Static Public Attributes
static final String TAG = `MainActivity`
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Detailed Description
Definition at line 24 of file MainActivity.java.
Member Function Documentation
void pt.lsts.asa.activities.MainActivity.back ()
Definition at line 225 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.pauseASA().
Referenced by pt.lsts.asa.activities.MainActivity.onBackPressed().
void pt.lsts.asa.activities.MainActivity.chooseActiveSystem (Context context)
Definition at line 108 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.createChooseActiveSystemDialog(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.SystemList.getList(), pt.lsts.asa.sys.SystemList.getNameList(), and pt.lsts.asa.ASA.getSystemList().
Referenced by pt.lsts.asa.activities.MainActivity.setChooseActiveSystemButton().
void pt.lsts.asa.activities.MainActivity.createChooseActiveSystemDialog (Context context, String[] array, final ArrayList< Sys > arrayListSys)
Definition at line 120 of file MainActivity.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.setActiveSys().
Referenced by pt.lsts.asa.activities.MainActivity.chooseActiveSystem().
void pt.lsts.asa.activities.MainActivity.onBackPressed ()
Definition at line 213 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.back().
void pt.lsts.asa.activities.MainActivity.onCreate (Bundle savedInstanceState) [protected]
Definition at line 37 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.setAutoButton(), pt.lsts.asa.activities.MainActivity.setChooseActiveSystemButton(), pt.lsts.asa.activities.MainActivity.setManualButton(), pt.lsts.asa.activities.MainActivity.setSettingsCheckListButton(), pt.lsts.asa.activities.MainActivity.setSystemListButton(), pt.lsts.asa.activities.MainActivity.setTest2Button(), and pt.lsts.asa.activities.MainActivity.setTestButton().
boolean pt.lsts.asa.activities.MainActivity.onCreateOptionsMenu (Menu menu)
Definition at line 183 of file MainActivity.java.
boolean pt.lsts.asa.activities.MainActivity.onOptionsItemSelected (MenuItem item)
Definition at line 190 of file MainActivity.java.
void pt.lsts.asa.activities.MainActivity.onPause ()
Definition at line 202 of file MainActivity.java.
void pt.lsts.asa.activities.MainActivity.onResume ()
Definition at line 207 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.resumeASA().
void pt.lsts.asa.activities.MainActivity.pauseASA ()
Definition at line 231 of file MainActivity.java.
References pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.ASA.pause(), and pt.lsts.asa.ASA.started.
Referenced by pt.lsts.asa.activities.MainActivity.back().
void pt.lsts.asa.activities.MainActivity.resumeASA ()
Definition at line 237 of file MainActivity.java.
References pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.ASA.start(), and pt.lsts.asa.ASA.started.
Referenced by pt.lsts.asa.activities.MainActivity.onResume().
void pt.lsts.asa.activities.MainActivity.setAutoButton ()
Definition at line 171 of file MainActivity.java.
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setChooseActiveSystemButton (final Context context)
Definition at line 99 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.chooseActiveSystem().
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setManualButton ()
Definition at line 160 of file MainActivity.java.
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setSettingsCheckListButton ()
Definition at line 149 of file MainActivity.java.
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setSystemListButton ()
Definition at line 60 of file MainActivity.java.
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setTest2Button ()
Definition at line 140 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.test2().
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.setTestButton ()
Definition at line 131 of file MainActivity.java.
References pt.lsts.asa.activities.MainActivity.test().
Referenced by pt.lsts.asa.activities.MainActivity.onCreate().
void pt.lsts.asa.activities.MainActivity.test ()
Definition at line 71 of file MainActivity.java.
References pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.settings.Settings.getBoolean(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getString(), pt.lsts.asa.settings.Settings.getType(), and pt.lsts.asa.util.AndroidUtil.showToastLong().
Referenced by pt.lsts.asa.activities.MainActivity.setTestButton().
void pt.lsts.asa.activities.MainActivity.test2 ()
Definition at line 91 of file MainActivity.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getName(), and pt.lsts.asa.util.AndroidUtil.showToastLong().
Referenced by pt.lsts.asa.activities.MainActivity.setTest2Button().
Member Data Documentation
final String pt.lsts.asa.activities.MainActivity.TAG = `MainActivity` [static]
Definition at line 26 of file MainActivity.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/activities/MainActivity.java