pt.lsts.asa.util.MUtil Class Reference
Static Public Member Functions
static double roundn (double d, int n)
static String getLocalIpAddress ()
static String getBroadcastAddress (Context mContext) throws IOException
static Bitmap requestBitmap (double requestLat1, double requestLon1, double requestLat2, double requestLon2, int w, int h)
static double nomalizeAngleRads2Pi (double angle)
static double nomalizeAngleRadsPi (double angle)
static double nomalizeAngleDegrees360 (double angle)
static double nomalizeAngleDegrees180 (double angle)
Static Public Attributes
static final double TWO_PI_RADS = Math.PI * 2.0
Static Private Attributes
static final String TAG = `MUtil`
Detailed Description
Class that gathers miscellaneous utilitary functions that don't really fit anywhere If I have a bunch of them in the same category i move them to a separate class
Author
jqcorreia
Definition at line 33 of file MUtil.java.
Member Function Documentation
static String pt.lsts.asa.util.MUtil.getBroadcastAddress (Context mContext) throws IOException [static]
Definition at line 81 of file MUtil.java.
Referenced by pt.lsts.asa.ASA.initBroadcast().
static String pt.lsts.asa.util.MUtil.getLocalIpAddress () [static]
Android function to retrieve the IP independent of the connection used (3G or WiFi)
Returns
string containing the IP
Definition at line 61 of file MUtil.java.
Referenced by pt.lsts.asa.comms.Announcer.generateAnnounce(), and pt.lsts.asa.managers.IMCManager.IMCManager().
static double pt.lsts.asa.util.MUtil.nomalizeAngleDegrees180 (double angle) [static]
Parameters
angle
Returns
the angle between -180 and 180
Definition at line 209 of file MUtil.java.
static double pt.lsts.asa.util.MUtil.nomalizeAngleDegrees360 (double angle) [static]
Parameters
angle
Returns
the angle between 0 and 360
Definition at line 197 of file MUtil.java.
static double pt.lsts.asa.util.MUtil.nomalizeAngleRads2Pi (double angle) [static]
Parameters
angle
Returns
the angle between 0 and 2pi
Definition at line 172 of file MUtil.java.
References pt.lsts.asa.util.MUtil.TWO_PI_RADS.
static double pt.lsts.asa.util.MUtil.nomalizeAngleRadsPi (double angle) [static]
Parameters
angle
Returns
the angle between -pi and pi
Definition at line 184 of file MUtil.java.
References pt.lsts.asa.util.MUtil.TWO_PI_RADS.
static Bitmap pt.lsts.asa.util.MUtil.requestBitmap (double requestLat1, double requestLon1, double requestLat2, double requestLon2, int w, int h) [static]
Definition at line 95 of file MUtil.java.
static double pt.lsts.asa.util.MUtil.roundn (double d, int n) [static]
Function that rounds a number to N decimal places
Parameters
d Double to round
n Number of decimal places to round to
Returns
Definition at line 48 of file MUtil.java.
Member Data Documentation
final String pt.lsts.asa.util.MUtil.TAG = `MUtil` [static], [private]
Definition at line 35 of file MUtil.java.
final double pt.lsts.asa.util.MUtil.TWO_PI_RADS = Math.PI * 2.0 [static]
Definition at line 37 of file MUtil.java.
Referenced by pt.lsts.asa.util.MUtil.nomalizeAngleRads2Pi(), and pt.lsts.asa.util.MUtil.nomalizeAngleRadsPi().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/MUtil.java