pt.lsts.asa.activities.SettingsActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
void populateCategories (Vector< PreferenceCategory > preferenceCategories)
void createProfileCategory (PreferenceCategory preferenceCategory)
Detailed Description
Definition at line 13 of file SettingsActivity.java.
Member Function Documentation
void pt.lsts.asa.activities.SettingsActivity.createProfileCategory (PreferenceCategory preferenceCategory)
Definition at line 46 of file SettingsActivity.java.
References pt.lsts.asa.settings.SettingsFactory.fetchPreferencesButtons().
Referenced by pt.lsts.asa.activities.SettingsActivity.populateCategories().
void pt.lsts.asa.activities.SettingsActivity.onCreate (Bundle savedInstanceState)
Definition at line 18 of file SettingsActivity.java.
References pt.lsts.asa.settings.SettingsFactory.fetchCategories(), and pt.lsts.asa.activities.SettingsActivity.populateCategories().
void pt.lsts.asa.activities.SettingsActivity.populateCategories (Vector< PreferenceCategory > preferenceCategories)
Definition at line 35 of file SettingsActivity.java.
References pt.lsts.asa.activities.SettingsActivity.createProfileCategory(), and pt.lsts.asa.settings.SettingsFactory.populate().
Referenced by pt.lsts.asa.activities.SettingsActivity.onCreate().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/activities/SettingsActivity.java