pt.lsts.asa.sys.SystemList Class Reference
Public Member Functions
SystemList (IMCManager imm)
void addSystemListChangeListener (SystemListChangeListener l)
void changeList (ArrayList< Sys > list)
boolean containsSysName (String name)
boolean containsSysId (int id)
Sys findSysByName (String name)
Sys findSysById (int id)
ArrayList< Sys > getList ()
ArrayList< String > getNameList ()
ArrayList< String > getNameListByType (String type)
void start ()
void stop ()
Static Public Attributes
static final String TAG = `SystemList`
static final int CONNECTED_TIME_LIMIT = 5000
static final boolean DEBUG = false
Private Member Functions
void checkConnection ()
Detailed Description
Definition at line 11 of file SystemList.java.
Constructor & Destructor Documentation
pt.lsts.asa.sys.SystemList.SystemList (IMCManager imm)
Definition at line 27 of file SystemList.java.
Member Function Documentation
void pt.lsts.asa.sys.SystemList.addSystemListChangeListener (SystemListChangeListener l)
Definition at line 55 of file SystemList.java.
void pt.lsts.asa.sys.SystemList.changeList (ArrayList< Sys > list)
Definition at line 59 of file SystemList.java.
Referenced by pt.lsts.asa.sys.SystemList.checkConnection(), and pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
void pt.lsts.asa.sys.SystemList.checkConnection () [private]
Definition at line 33 of file SystemList.java.
References pt.lsts.asa.sys.SystemList.changeList().
boolean pt.lsts.asa.sys.SystemList.containsSysId (int id)
Definition at line 73 of file SystemList.java.
boolean pt.lsts.asa.sys.SystemList.containsSysName (String name)
Definition at line 65 of file SystemList.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
Sys pt.lsts.asa.sys.SystemList.findSysById (int id)
Definition at line 89 of file SystemList.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
Sys pt.lsts.asa.sys.SystemList.findSysByName (String name)
Definition at line 81 of file SystemList.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.colorItems(), pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
ArrayList<Sys> pt.lsts.asa.sys.SystemList.getList ()
Definition at line 97 of file SystemList.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.activities.MainActivity.chooseActiveSystem(), pt.lsts.asa.fragments.SystemListFragment.colorItems(), and pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
ArrayList<String> pt.lsts.asa.sys.SystemList.getNameList ()
Definition at line 101 of file SystemList.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), and pt.lsts.asa.activities.MainActivity.chooseActiveSystem().
ArrayList<String> pt.lsts.asa.sys.SystemList.getNameListByType (String type)
Definition at line 109 of file SystemList.java.
void pt.lsts.asa.sys.SystemList.start ()
Definition at line 118 of file SystemList.java.
Referenced by pt.lsts.asa.ASA.start().
void pt.lsts.asa.sys.SystemList.stop ()
Definition at line 122 of file SystemList.java.
Referenced by pt.lsts.asa.ASA.pause().
Member Data Documentation
final int pt.lsts.asa.sys.SystemList.CONNECTED_TIME_LIMIT = 5000 [static]
Definition at line 14 of file SystemList.java.
final boolean pt.lsts.asa.sys.SystemList.DEBUG = false [static]
Definition at line 15 of file SystemList.java.
final String pt.lsts.asa.sys.SystemList.TAG = `SystemList` [static]
Definition at line 13 of file SystemList.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/sys/SystemList.java