pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber Class Reference
Public Member Functions
LblBeaconListIMCSubscriber (LblBeaconList lblBeaconList)
void onReceive (final IMCMessage msg)
Static Public Attributes
static final String[] SUBSCRIBED_MSGS = { `LblConfig` }
static final String TAG = `LblBeaconList`
Private Attributes
LblBeaconList lblBeaconList
Thread thread
Detailed Description
Definition at line 10 of file LblBeaconListIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.LblBeaconListIMCSubscriber (LblBeaconList lblBeaconList)
Definition at line 17 of file LblBeaconListIMCSubscriber.java.
References pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.lblBeaconList.
Member Function Documentation
void pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 22 of file LblBeaconListIMCSubscriber.java.
References pt.lsts.asa.pos.LblBeaconList.getList(), pt.lsts.asa.pos.LblBeaconList.notifyListeners(), pt.lsts.asa.pos.Beacon.setInterrogationChannel(), pt.lsts.asa.pos.Beacon.setReplyChannel(), and pt.lsts.asa.pos.Beacon.setTransponderDelay().
Member Data Documentation
LblBeaconList pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.lblBeaconList [private]
Definition at line 14 of file LblBeaconListIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.LblBeaconListIMCSubscriber().
final String [] pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.SUBSCRIBED_MSGS = { `LblConfig` } [static]
Definition at line 12 of file LblBeaconListIMCSubscriber.java.
Referenced by pt.lsts.asa.ASA.addInitialSubscribers().
final String pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.TAG = `LblBeaconList` [static]
Definition at line 13 of file LblBeaconListIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.thread [private]
Definition at line 15 of file LblBeaconListIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/LblBeaconListIMCSubscriber.java