pt.lsts.asa.settings.Settings Class Reference
Static Public Member Functions
static Settings getSettings ()
static SharedPreferences getSharedPreferences ()
static boolean putFullString (String key, String value)
static boolean putString (String key, String value)
static boolean putInt (String key, int value)
static boolean putBoolean (String key, boolean value)
static boolean clear ()
static Map< String,?> getAll ()
static boolean isOptions (String key)
static boolean hasOptions (String key)
static String[] getOptions (String key)
static boolean exists (String key)
static String getType (String key, String defValue)
static String getCategory (String key, String defValue)
static String getKey (String key, String defValue)
static String getDescription (String key, String defValue)
static String getString (String key, String defValue)
static String[] getStrings (String key, String[] defValue)
static int getInt (String key, int defValue)
static boolean getBoolean (String key, boolean defValue)
Private Member Functions
Settings ()
Static Private Attributes
static final String TAG = `Settings`
static Settings settings = null
Detailed Description
Definition at line 12 of file Settings.java.
Constructor & Destructor Documentation
pt.lsts.asa.settings.Settings.Settings () [private]
Definition at line 17 of file Settings.java.
Referenced by pt.lsts.asa.settings.Settings.getSettings().
Member Function Documentation
static boolean pt.lsts.asa.settings.Settings.clear () [static]
Definition at line 87 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.Profile.load().
static boolean pt.lsts.asa.settings.Settings.exists (String key) [static]
Definition at line 119 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.Settings.hasOptions(), and pt.lsts.asa.settings.Settings.isOptions().
static Map<String, ?> pt.lsts.asa.settings.Settings.getAll () [static]
Definition at line 91 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchCategories(), pt.lsts.asa.App.initSettings(), pt.lsts.asa.settings.SettingsFactory.populate(), pt.lsts.asa.settings.Profile.save(), and pt.lsts.asa.activities.MainActivity.test().
static boolean pt.lsts.asa.settings.Settings.getBoolean (String key, boolean defValue) [static]
Definition at line 181 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.fragments.SystemListFragment.filterSys(), pt.lsts.asa.feedback.CallOut.initBooleans(), pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged(), pt.lsts.asa.settings.SettingsFactory.populate(), and pt.lsts.asa.activities.MainActivity.test().
static String pt.lsts.asa.settings.Settings.getCategory (String key, String defValue) [static]
Definition at line 130 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchCategories(), pt.lsts.asa.settings.SettingsFactory.populate(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), pt.lsts.asa.settings.Settings.putString(), and pt.lsts.asa.activities.MainActivity.test().
static String pt.lsts.asa.settings.Settings.getDescription (String key, String defValue) [static]
Definition at line 145 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), pt.lsts.asa.settings.Settings.putString(), pt.lsts.asa.settings.SettingsFactory.setOnChangeListener(), pt.lsts.asa.settings.SettingsFactory.setOnChangeListenerList(), and pt.lsts.asa.activities.MainActivity.test().
static int pt.lsts.asa.settings.Settings.getInt (String key, int defValue) [static]
Definition at line 173 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.feedback.CallOut.initIntervals(), pt.lsts.asa.feedback.CallOut.initTextToSpeech(), pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged(), pt.lsts.asa.listenners.sharedPreferences.ManualIndicatorsPreferencesListenner.onPreferenceChanged(), pt.lsts.asa.settings.SettingsFactory.populate(), and pt.lsts.asa.activities.MainActivity.test().
static String pt.lsts.asa.settings.Settings.getKey (String key, String defValue) [static]
Definition at line 138 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), pt.lsts.asa.settings.Settings.putString(), and pt.lsts.asa.activities.MainActivity.test().
static String [] pt.lsts.asa.settings.Settings.getOptions (String key) [static]
Definition at line 110 of file Settings.java.
References pt.lsts.asa.settings.Settings.getStrings(), and pt.lsts.asa.settings.Settings.hasOptions().
Referenced by pt.lsts.asa.settings.SettingsFactory.populate().
static Settings pt.lsts.asa.settings.Settings.getSettings () [static]
Definition at line 21 of file Settings.java.
References pt.lsts.asa.settings.Settings.settings, and pt.lsts.asa.settings.Settings.Settings().
Referenced by pt.lsts.asa.App.initSettings().
static SharedPreferences pt.lsts.asa.settings.Settings.getSharedPreferences () [static]
Definition at line 28 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.changeValue().
static String pt.lsts.asa.settings.Settings.getString (String key, String defValue) [static]
Definition at line 153 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry(), pt.lsts.asa.util.StringUtils.getAirCamUrl(), pt.lsts.asa.util.StringUtils.getAxisUrl(), pt.lsts.asa.util.StringUtils.getCamUrl(), pt.lsts.asa.settings.SettingsFactory.populate(), and pt.lsts.asa.activities.MainActivity.test().
static String [] pt.lsts.asa.settings.Settings.getStrings (String key, String[] defValue) [static]
Definition at line 161 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.Settings.getOptions().
static String pt.lsts.asa.settings.Settings.getType (String key, String defValue) [static]
Definition at line 123 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.populate(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), pt.lsts.asa.settings.Settings.putString(), and pt.lsts.asa.activities.MainActivity.test().
static boolean pt.lsts.asa.settings.Settings.hasOptions (String key) [static]
Definition at line 103 of file Settings.java.
References pt.lsts.asa.settings.Settings.exists().
Referenced by pt.lsts.asa.settings.Settings.getOptions(), and pt.lsts.asa.settings.SettingsFactory.populate().
static boolean pt.lsts.asa.settings.Settings.isOptions (String key) [static]
Definition at line 95 of file Settings.java.
References pt.lsts.asa.settings.Settings.exists().
Referenced by pt.lsts.asa.settings.SettingsFactory.populate().
static boolean pt.lsts.asa.settings.Settings.putBoolean (String key, boolean value) [static]
Definition at line 71 of file Settings.java.
References pt.lsts.asa.ASA.getBus(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getType(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.changeValue().
static boolean pt.lsts.asa.settings.Settings.putFullString (String key, String value) [static]
Definition at line 32 of file Settings.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.Profile.loadSetting().
static boolean pt.lsts.asa.settings.Settings.putInt (String key, int value) [static]
Definition at line 55 of file Settings.java.
References pt.lsts.asa.ASA.getBus(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getType(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.changeValue().
static boolean pt.lsts.asa.settings.Settings.putString (String key, String value) [static]
Definition at line 39 of file Settings.java.
References pt.lsts.asa.ASA.getBus(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getType(), and pt.lsts.asa.ASA.sharedPreferences.
Referenced by pt.lsts.asa.settings.SettingsFactory.changeValue().
Member Data Documentation
Settings pt.lsts.asa.settings.Settings.settings = null [static], [private]
Definition at line 15 of file Settings.java.
Referenced by pt.lsts.asa.settings.Settings.getSettings().
final String pt.lsts.asa.settings.Settings.TAG = `Settings` [static], [private]
Definition at line 14 of file Settings.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/settings/Settings.java