pt.lsts.asa.handlers.AccuSmsHandler Class Reference
Public Member Functions
IMCManager getmManager ()
void setmManager (IMCManager mManager)
AccuSmsHandler (Context context)
void sendSms (String destination, String text, int timeout)
void stop ()
Private Attributes
IMCManager mManager
Context mContext
Detailed Description
Definition at line 10 of file AccuSmsHandler.java.
Constructor & Destructor Documentation
pt.lsts.asa.handlers.AccuSmsHandler.AccuSmsHandler (Context context)
Definition at line 24 of file AccuSmsHandler.java.
Member Function Documentation
IMCManager pt.lsts.asa.handlers.AccuSmsHandler.getmManager ()
Definition at line 16 of file AccuSmsHandler.java.
References pt.lsts.asa.handlers.AccuSmsHandler.mManager.
Referenced by pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.onReceive().
void pt.lsts.asa.handlers.AccuSmsHandler.sendSms (String destination, String text, int timeout)
Definition at line 28 of file AccuSmsHandler.java.
Referenced by pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.onReceive().
void pt.lsts.asa.handlers.AccuSmsHandler.setmManager (IMCManager mManager)
Definition at line 20 of file AccuSmsHandler.java.
References pt.lsts.asa.handlers.AccuSmsHandler.mManager.
void pt.lsts.asa.handlers.AccuSmsHandler.stop ()
Definition at line 35 of file AccuSmsHandler.java.
Referenced by pt.lsts.asa.ASA.pause().
Member Data Documentation
Context pt.lsts.asa.handlers.AccuSmsHandler.mContext [private]
Definition at line 13 of file AccuSmsHandler.java.
IMCManager pt.lsts.asa.handlers.AccuSmsHandler.mManager [private]
Definition at line 12 of file AccuSmsHandler.java.
Referenced by pt.lsts.asa.handlers.AccuSmsHandler.getmManager(), and pt.lsts.asa.handlers.AccuSmsHandler.setmManager().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/handlers/AccuSmsHandler.java