pt.lsts.asa.util.AndroidUtil Class Reference
Static Public Member Functions
static void showToastShort (FragmentActivity fragmentActivity, final String msg)
static void showToastLong (FragmentActivity fragmentActivity, final String msg)
static void loadFragment (FragmentActivity fragmentActivity, Fragment fragment, int fragmentContainerID)
Detailed Description
Created by jloureiro on 1/8/15.
Definition at line 12 of file AndroidUtil.java.
Member Function Documentation
static void pt.lsts.asa.util.AndroidUtil.loadFragment (FragmentActivity fragmentActivity, Fragment fragment, int fragmentContainerID) [static]
Definition at line 31 of file AndroidUtil.java.
Referenced by pt.lsts.asa.activities.AutoActivity.loadFragments(), pt.lsts.asa.activities.ManualActivity.loadFragments(), and pt.lsts.asa.activities.SystemListActivity.loadFragments().
static void pt.lsts.asa.util.AndroidUtil.showToastLong (FragmentActivity fragmentActivity, final String msg) [static]
Definition at line 23 of file AndroidUtil.java.
References pt.lsts.asa.ASA.getContext().
Referenced by pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), pt.lsts.asa.fragments.VideoViewFragment.setRunnable(), pt.lsts.asa.fragments.SystemListFragment.showMoreInfo(), pt.lsts.asa.activities.MainActivity.test(), and pt.lsts.asa.activities.MainActivity.test2().
static void pt.lsts.asa.util.AndroidUtil.showToastShort (FragmentActivity fragmentActivity, final String msg) [static]
Definition at line 15 of file AndroidUtil.java.
References pt.lsts.asa.ASA.getContext().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.setRunnable(), and pt.lsts.asa.fragments.VideoViewFragment.setVideoViewListeners().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/AndroidUtil.java