pt.lsts.asa.util.FileOperations Class Reference
Static Public Member Functions
static void initDir (File dir)
static boolean isExternalStorageWritable ()
static boolean isExternalStorageReadable ()
static void copyFile (InputStream in, OutputStream out) throws IOException
static void copyFile (File fileIn, File fileOut) throws IOException
static Vector< String > readLines (File file)
static Vector< String > readLines (InputStream in)
static void writeLine (String line, OutputStream out)
static void writeLines (Vector< String > lines, OutputStream out)
static void writeLine (String line, File file)
static void writeLines (Vector< String > lines, File file)
static String[] filterFilesByExtension (String[] filesArray, String extension)
static String[] removeExtension (String[] filesArray, String extension)
static void copyAllAssets (Context context)
static boolean copySpecificAsset (Context context, String name)
Static Public Attributes
static File mainDir
Detailed Description
Definition at line 18 of file FileOperations.java.
Member Function Documentation
static void pt.lsts.asa.util.FileOperations.copyAllAssets (Context context) [static]
Definition at line 137 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.copyFile(), and pt.lsts.asa.util.FileOperations.initDir().
static void pt.lsts.asa.util.FileOperations.copyFile (InputStream in, OutputStream out) throws IOException [static]
Definition at line 46 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.readLines(), and pt.lsts.asa.util.FileOperations.writeLines().
Referenced by pt.lsts.asa.util.FileOperations.copyAllAssets(), and pt.lsts.asa.util.FileOperations.copySpecificAsset().
static void pt.lsts.asa.util.FileOperations.copyFile (File fileIn, File fileOut) throws IOException [static]
Definition at line 51 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.readLines(), and pt.lsts.asa.util.FileOperations.writeLines().
static boolean pt.lsts.asa.util.FileOperations.copySpecificAsset (Context context, String name) [static]
Definition at line 165 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.copyFile(), and pt.lsts.asa.util.FileOperations.initDir().
Referenced by pt.lsts.asa.App.initSettings().
static String [] pt.lsts.asa.util.FileOperations.filterFilesByExtension (String[] filesArray, String extension) [static]
Definition at line 114 of file FileOperations.java.
Referenced by pt.lsts.asa.settings.Profile.getProfilesAvailable().
static void pt.lsts.asa.util.FileOperations.initDir (File dir) [static]
Definition at line 23 of file FileOperations.java.
Referenced by pt.lsts.asa.util.FileOperations.copyAllAssets(), pt.lsts.asa.util.FileOperations.copySpecificAsset(), and pt.lsts.asa.settings.Profile.save().
static boolean pt.lsts.asa.util.FileOperations.isExternalStorageReadable () [static]
Definition at line 37 of file FileOperations.java.
static boolean pt.lsts.asa.util.FileOperations.isExternalStorageWritable () [static]
Definition at line 28 of file FileOperations.java.
static Vector<String> pt.lsts.asa.util.FileOperations.readLines (File file) [static]
Definition at line 55 of file FileOperations.java.
Referenced by pt.lsts.asa.util.FileOperations.copyFile(), and pt.lsts.asa.settings.Profile.load().
static Vector<String> pt.lsts.asa.util.FileOperations.readLines (InputStream in) [static]
Definition at line 64 of file FileOperations.java.
static String [] pt.lsts.asa.util.FileOperations.removeExtension (String[] filesArray, String extension) [static]
Definition at line 127 of file FileOperations.java.
Referenced by pt.lsts.asa.settings.Profile.getProfilesAvailable().
static void pt.lsts.asa.util.FileOperations.writeLine (String line, OutputStream out) [static]
Definition at line 81 of file FileOperations.java.
Referenced by pt.lsts.asa.util.FileOperations.writeLine(), and pt.lsts.asa.util.FileOperations.writeLines().
static void pt.lsts.asa.util.FileOperations.writeLine (String line, File file) [static]
Definition at line 96 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.writeLine().
static void pt.lsts.asa.util.FileOperations.writeLines (Vector< String > lines, OutputStream out) [static]
Definition at line 91 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.writeLine().
Referenced by pt.lsts.asa.util.FileOperations.copyFile(), pt.lsts.asa.settings.Profile.save(), and pt.lsts.asa.util.FileOperations.writeLines().
static void pt.lsts.asa.util.FileOperations.writeLines (Vector< String > lines, File file) [static]
Definition at line 105 of file FileOperations.java.
References pt.lsts.asa.util.FileOperations.writeLines().
Member Data Documentation
File pt.lsts.asa.util.FileOperations.mainDir [static]
Initial value:
= new File(
            "/storage/emulated/0/Android/data/pt.lsts.ASA/")
Definition at line 20 of file FileOperations.java.
Referenced by pt.lsts.asa.settings.Profile.getProfilesAvailable(), pt.lsts.asa.settings.Profile.load(), and pt.lsts.asa.settings.Profile.save().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/FileOperations.java