pt.lsts.asa.managers.IMCManager Class Reference
Public Member Functions
IMCManager ()
LinkedHashMap< Integer, List< IMCSubscriber > > getSubscribers ()
ArrayList< IMCSubscriber > getSubscribersToAll ()
boolean addSubscriber (IMCSubscriber sub, String abbrevName)
void addSubscriber (IMCSubscriber sub, String[] abbrevNameList)
void addSubscriberToAllMessages (IMCSubscriber sub)
void removeSubscriberToAll (IMCSubscriber sub)
void processMessage (IMCMessage message)
void onMessage (MessageInfo info, IMCMessage message)
void killComms ()
void startComms ()
UDPTransport getComm ()
UDPTransport getListener ()
int getLocalId ()
void sendToActiveSys (String name, Object...values)
void sendToActiveSys (IMCMessage msg)
void sendToSys (Sys sys, String name, Object...values)
void sendToSys (Sys sys, IMCMessage msg)
void send (String address, int port, String name, Object...values)
void send (final String address, final int port, final IMCMessage msg)
void printUsedTypes ()
Public Attributes
boolean commActive = false
Static Public Attributes
static final String TAG = `IMCManager`
Private Member Functions
void fillHeader (IMCMessage msg)
Detailed Description
Class that aggregates IMC messaging functions and delivers message to the subscribers
Author
jqcorreia
Definition at line 30 of file IMCManager.java.
Constructor & Destructor Documentation
pt.lsts.asa.managers.IMCManager.IMCManager ()
Definition at line 42 of file IMCManager.java.
References pt.lsts.asa.util.MUtil.getLocalIpAddress().
Member Function Documentation
boolean pt.lsts.asa.managers.IMCManager.addSubscriber (IMCSubscriber sub, String abbrevName)
Function that adds a subscriber class to the message system, registering for a given id
Parameters
sub
mgid
Definition at line 71 of file IMCManager.java.
Referenced by pt.lsts.asa.ASA.addSubscriber(), and pt.lsts.asa.managers.IMCManager.addSubscriber().
void pt.lsts.asa.managers.IMCManager.addSubscriber (IMCSubscriber sub, String[] abbrevNameList)
Batch method to add subscribers
Parameters
sub IMCSubscriber
abbrevNameList Array of strings containing the names of messages to subscribe
Definition at line 102 of file IMCManager.java.
References pt.lsts.asa.managers.IMCManager.addSubscriber().
void pt.lsts.asa.managers.IMCManager.addSubscriberToAllMessages (IMCSubscriber sub)
Definition at line 108 of file IMCManager.java.
Referenced by pt.lsts.asa.ASA.addSubscriber().
void pt.lsts.asa.managers.IMCManager.fillHeader (IMCMessage msg) [private]
Definition at line 285 of file IMCManager.java.
Referenced by pt.lsts.asa.managers.IMCManager.send().
UDPTransport pt.lsts.asa.managers.IMCManager.getComm ()
Definition at line 220 of file IMCManager.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
UDPTransport pt.lsts.asa.managers.IMCManager.getListener ()
Definition at line 224 of file IMCManager.java.
int pt.lsts.asa.managers.IMCManager.getLocalId ()
Definition at line 228 of file IMCManager.java.
Referenced by pt.lsts.asa.comms.Announcer.generateAnnounce(), and pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.onReceive().
LinkedHashMap<Integer, List<IMCSubscriber> > pt.lsts.asa.managers.IMCManager.getSubscribers ()
Definition at line 56 of file IMCManager.java.
ArrayList<IMCSubscriber> pt.lsts.asa.managers.IMCManager.getSubscribersToAll ()
Definition at line 60 of file IMCManager.java.
void pt.lsts.asa.managers.IMCManager.killComms ()
Definition at line 188 of file IMCManager.java.
Referenced by pt.lsts.asa.ASA.pause().
void pt.lsts.asa.managers.IMCManager.onMessage (MessageInfo info, IMCMessage message)
Definition at line 184 of file IMCManager.java.
void pt.lsts.asa.managers.IMCManager.printUsedTypes ()
Definition at line 291 of file IMCManager.java.
void pt.lsts.asa.managers.IMCManager.processMessage (IMCMessage message)
Method that delivers the message to the various subscribers. Leaving the task of seeing which is the Active Sys to the various components for low level flexibility.
Parameters
message Message to be delivered
Definition at line 137 of file IMCManager.java.
void pt.lsts.asa.managers.IMCManager.removeSubscriberToAll (IMCSubscriber sub)
Function that unsubscribes every message sent to a component
Parameters
sub Subscriber component to remove
Definition at line 120 of file IMCManager.java.
void pt.lsts.asa.managers.IMCManager.send (String address, int port, String name, Object... values)
Definition at line 257 of file IMCManager.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), and pt.lsts.asa.managers.IMCManager.sendToSys().
void pt.lsts.asa.managers.IMCManager.send (final String address, final int port, final IMCMessage msg)
Method responsible for effectively giving the order to the UDPTransport to send the message
Definition at line 270 of file IMCManager.java.
References pt.lsts.asa.managers.IMCManager.fillHeader().
void pt.lsts.asa.managers.IMCManager.sendToActiveSys (String name, Object... values)
Definition at line 233 of file IMCManager.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.managers.IMCManager.sendToSys().
void pt.lsts.asa.managers.IMCManager.sendToActiveSys (IMCMessage msg)
Definition at line 237 of file IMCManager.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.managers.IMCManager.sendToSys().
void pt.lsts.asa.managers.IMCManager.sendToSys (Sys sys, String name, Object... values)
Definition at line 241 of file IMCManager.java.
References pt.lsts.asa.sys.Sys.getAddress(), pt.lsts.asa.sys.Sys.getPort(), and pt.lsts.asa.managers.IMCManager.send().
Referenced by pt.lsts.asa.feedback.Heart.sendHeartbeat(), and pt.lsts.asa.managers.IMCManager.sendToActiveSys().
void pt.lsts.asa.managers.IMCManager.sendToSys (Sys sys, IMCMessage msg)
Definition at line 249 of file IMCManager.java.
References pt.lsts.asa.sys.Sys.getAddress(), pt.lsts.asa.sys.Sys.getPort(), and pt.lsts.asa.managers.IMCManager.send().
void pt.lsts.asa.managers.IMCManager.startComms ()
Definition at line 204 of file IMCManager.java.
Referenced by pt.lsts.asa.ASA.initIMCManager(), and pt.lsts.asa.ASA.start().
Member Data Documentation
boolean pt.lsts.asa.managers.IMCManager.commActive = false
Definition at line 39 of file IMCManager.java.
final String pt.lsts.asa.managers.IMCManager.TAG = `IMCManager` [static]
Definition at line 31 of file IMCManager.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/managers/IMCManager.java