pt.lsts.asa.settings.Profile Class Reference
Static Public Member Functions
static String restoreDefaults ()
static String load (String name)
static void loadSetting (String setting)
static String save (String name)
static String[] getProfilesAvailable ()
Static Public Attributes
static final String TAG = `Profile`
static String defaultSettingsName = `default_settings`
static File defaultSettingsFile
static String firstLineInCsvFile = `type,category,key,description,value(s)`
static final String extension = `csv`
Detailed Description
Definition at line 12 of file Profile.java.
Member Function Documentation
static String [] pt.lsts.asa.settings.Profile.getProfilesAvailable () [static]
Definition at line 96 of file Profile.java.
References pt.lsts.asa.util.FileOperations.filterFilesByExtension(), pt.lsts.asa.util.FileOperations.mainDir, and pt.lsts.asa.util.FileOperations.removeExtension().
Referenced by pt.lsts.asa.settings.SettingsFactory.load().
static String pt.lsts.asa.settings.Profile.load (String name) [static]
Definition at line 25 of file Profile.java.
References pt.lsts.asa.settings.Settings.clear(), pt.lsts.asa.settings.Profile.loadSetting(), pt.lsts.asa.util.FileOperations.mainDir, and pt.lsts.asa.util.FileOperations.readLines().
Referenced by pt.lsts.asa.settings.SettingsFactory.load(), and pt.lsts.asa.settings.Profile.restoreDefaults().
static void pt.lsts.asa.settings.Profile.loadSetting (String setting) [static]
Definition at line 39 of file Profile.java.
References pt.lsts.asa.settings.Settings.putFullString(), and pt.lsts.asa.util.StringUtils.validateSetting().
Referenced by pt.lsts.asa.settings.Profile.load().
static String pt.lsts.asa.settings.Profile.restoreDefaults () [static]
Definition at line 21 of file Profile.java.
References pt.lsts.asa.settings.Profile.load().
Referenced by pt.lsts.asa.App.initSettings(), and pt.lsts.asa.settings.SettingsFactory.restoreDefaults().
static String pt.lsts.asa.settings.Profile.save (String name) [static]
Definition at line 75 of file Profile.java.
References pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.util.FileOperations.initDir(), pt.lsts.asa.util.FileOperations.mainDir, and pt.lsts.asa.util.FileOperations.writeLines().
Referenced by pt.lsts.asa.settings.SettingsFactory.save().
Member Data Documentation
File pt.lsts.asa.settings.Profile.defaultSettingsFile [static]
Initial value:
= new File(FileOperations.mainDir,
            defaultSettingsName)
Definition at line 16 of file Profile.java.
String pt.lsts.asa.settings.Profile.defaultSettingsName = `default_settings` [static]
Definition at line 15 of file Profile.java.
final String pt.lsts.asa.settings.Profile.extension = `csv` [static]
Definition at line 19 of file Profile.java.
String pt.lsts.asa.settings.Profile.firstLineInCsvFile = `type,category,key,description,value(s)` [static]
Definition at line 18 of file Profile.java.
final String pt.lsts.asa.settings.Profile.TAG = `Profile` [static]
Definition at line 14 of file Profile.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/settings/Profile.java