pt.lsts.asa.util.CoordUtil Class Reference
Static Public Member Functions
static double[] latLonDiff (double lat, double lon, double alat, double alon)
static double[] getAbsoluteLatLonDepth (double latitude, double longitude, double depth, double offsetNorth, double offsetEast, double offsetDown)
static double[] getAbsoluteLatLonDepthFromMsg (IMCMessage msg)
static double[] latLonAddNE2 (double lat, double lon, double north, double east)
static double dist2LatLon (double lat1, double lon1, double lat2, double lon2)
static double bearing2LatLon (double lat1, double lon1, double lat2, double lon2)
static String degreesToDMS (double deg, boolean isLat)
Static Public Attributes
static double msToKnot = 1.9438612860586
Detailed Description
Definition at line 7 of file CoordUtil.java.
Member Function Documentation
static double pt.lsts.asa.util.CoordUtil.bearing2LatLon (double lat1, double lon1, double lat2, double lon2) [static]
The heading that point 1 needs to follow to get to point 2
Parameters
lat1
lon1
lat2
lon2
Returns
Bearing in degress (0 to 360 degrees)
Definition at line 181 of file CoordUtil.java.
static String pt.lsts.asa.util.CoordUtil.degreesToDMS (double deg, boolean isLat) [static]
Parameters
deg Degrees to convert
isLat boolean to check if it is a latitude, if false the calculation is done assuming longitude
Returns
String expressing the conversion in the DºM'S" format
Definition at line 206 of file CoordUtil.java.
Referenced by pt.lsts.asa.pos.Beacon.getLatDMS(), and pt.lsts.asa.pos.Beacon.getLonDMS().
static double pt.lsts.asa.util.CoordUtil.dist2LatLon (double lat1, double lon1, double lat2, double lon2) [static]
Distance between 2 LatLon points (ignoring depth)
Parameters
lat1
lon1
lat2
lon2
Returns
the distance between the 2 points in Kilometers
Definition at line 157 of file CoordUtil.java.
static double [] pt.lsts.asa.util.CoordUtil.getAbsoluteLatLonDepth (double latitude, double longitude, double depth, double offsetNorth, double offsetEast, double offsetDown) [static]
Modified by jqcorreia for ACCU
Returns
The total Lat(), Lon() and Depth(m)
Definition at line 37 of file CoordUtil.java.
References pt.lsts.asa.util.CoordUtil.latLonAddNE2().
Referenced by pt.lsts.asa.util.CoordUtil.getAbsoluteLatLonDepthFromMsg().
static double [] pt.lsts.asa.util.CoordUtil.getAbsoluteLatLonDepthFromMsg (IMCMessage msg) [static]
Returns an Absolute Position based solely on a IMCMessage This message has to be an EstimatedState (or equivalent)
Parameters
msg Message to process
Returns
Array of size 3 with Lat-Lon-Depth
Definition at line 74 of file CoordUtil.java.
References pt.lsts.asa.util.CoordUtil.getAbsoluteLatLonDepth().
static double [] pt.lsts.asa.util.CoordUtil.latLonAddNE2 (double lat, double lon, double north, double east) [static]
Add an offset in meters(north, east) to a (lat,lon) in decimal degrees Modified by jqcorreia for ACCU
Definition at line 112 of file CoordUtil.java.
References pt.lsts.asa.pos.GISCoordinate.getLatInDecDeg(), pt.lsts.asa.pos.GISCoordinate.getLonInDecDeg(), pt.lsts.asa.util.CoordUtil.latLonDiff(), pt.lsts.asa.pos.GISCoordinate.move(), and pt.lsts.asa.pos.GISCoordinate.WGS84.
Referenced by pt.lsts.asa.util.CoordUtil.getAbsoluteLatLonDepth().
static double [] pt.lsts.asa.util.CoordUtil.latLonDiff (double lat, double lon, double alat, double alon) [static]
Definition at line 16 of file CoordUtil.java.
References pt.lsts.asa.pos.UTMCoordinates.getEasting(), and pt.lsts.asa.pos.UTMCoordinates.getNorthing().
Referenced by pt.lsts.asa.util.CoordUtil.latLonAddNE2().
Member Data Documentation
double pt.lsts.asa.util.CoordUtil.msToKnot = 1.9438612860586 [static]
Computes the offset (north, east) in meters from (lat, lon) to (alat, alon) [both of these in decimal degrees].
 Subtract the two latlons and come up with the distance in meters N/S and E/W between them.
Definition at line 14 of file CoordUtil.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/CoordUtil.java