pt.lsts.asa.fragments.GmapFragment Class Reference
Public Member Functions
GmapFragment ()
GmapFragment (FragmentActivity fragmentActivity)
FragmentActivity getFragmentActivity ()
GoogleMap getGoogleMap ()
LatLng getLastKnowLatLng ()
void onCreate (Bundle savedInstanceState)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onAttach (Activity activity)
void onDetach ()
void initIMCSubscriber ()
void onMapReady (GoogleMap map)
Marker addMarkerToPos (final Sys sys)
Marker addMarkerToPos (final Sys sys, final int iconRid)
void updateMyLocation (Location location)
void setActiveSysLatLng (final LatLng vehicleLatLng)
void setActiveSysPsi (final float psi)
void updateActiveSysMarker ()
void removeMarker (String title)
Static Public Attributes
static final String TAG = `GmapFragment`
Private Attributes
FragmentActivity fragmentActivity =null
GoogleMap googleMap = null
MapFragment mapFragment = null
LatLng myLatLng = new LatLng(0,0)
MyLocationListener myLocationListener = null
Boolean initZoom = false
ArrayList< Marker > markersArrayList = new ArrayList<Marker>()
Detailed Description
Definition at line 32 of file GmapFragment.java.
Constructor & Destructor Documentation
pt.lsts.asa.fragments.GmapFragment.GmapFragment ()
Definition at line 47 of file GmapFragment.java.
pt.lsts.asa.fragments.GmapFragment.GmapFragment (FragmentActivity fragmentActivity)
Definition at line 51 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.fragmentActivity, and pt.lsts.asa.listenners.MyLocationListener.initLocationListener().
Member Function Documentation
Marker pt.lsts.asa.fragments.GmapFragment.addMarkerToPos (final Sys sys)
Definition at line 107 of file GmapFragment.java.
References pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getLatLng(), pt.lsts.asa.sys.Sys.getMaker(), pt.lsts.asa.sys.Sys.getName(), pt.lsts.asa.sys.Sys.setMaker(), and pt.lsts.asa.ASA.UIThread.
Referenced by pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
Marker pt.lsts.asa.fragments.GmapFragment.addMarkerToPos (final Sys sys, final int iconRid)
Definition at line 128 of file GmapFragment.java.
References pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getLatLng(), pt.lsts.asa.sys.Sys.getMaker(), pt.lsts.asa.sys.Sys.getName(), pt.lsts.asa.sys.Sys.setMaker(), and pt.lsts.asa.ASA.UIThread.
FragmentActivity pt.lsts.asa.fragments.GmapFragment.getFragmentActivity ()
Definition at line 57 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.fragmentActivity.
Referenced by pt.lsts.asa.listenners.MyLocationListener.MyLocationListener().
GoogleMap pt.lsts.asa.fragments.GmapFragment.getGoogleMap ()
Definition at line 61 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.googleMap.
Referenced by pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive().
LatLng pt.lsts.asa.fragments.GmapFragment.getLastKnowLatLng ()
Definition at line 65 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.myLatLng.
void pt.lsts.asa.fragments.GmapFragment.initIMCSubscriber ()
Definition at line 94 of file GmapFragment.java.
References pt.lsts.asa.ASA.addSubscriber(), and pt.lsts.asa.ASA.getInstance().
Referenced by pt.lsts.asa.fragments.GmapFragment.onMapReady().
void pt.lsts.asa.fragments.GmapFragment.onAttach (Activity activity)
Definition at line 85 of file GmapFragment.java.
void pt.lsts.asa.fragments.GmapFragment.onCreate (Bundle savedInstanceState)
Definition at line 70 of file GmapFragment.java.
View pt.lsts.asa.fragments.GmapFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 75 of file GmapFragment.java.
void pt.lsts.asa.fragments.GmapFragment.onDetach ()
Definition at line 90 of file GmapFragment.java.
void pt.lsts.asa.fragments.GmapFragment.onMapReady (GoogleMap map)
Definition at line 100 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.initIMCSubscriber().
void pt.lsts.asa.fragments.GmapFragment.removeMarker (String title)
Definition at line 197 of file GmapFragment.java.
void pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng (final LatLng vehicleLatLng)
Definition at line 165 of file GmapFragment.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getName(), and pt.lsts.asa.sys.Sys.setLatLng().
Referenced by pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive().
void pt.lsts.asa.fragments.GmapFragment.setActiveSysPsi (final float psi)
Definition at line 171 of file GmapFragment.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.sys.Sys.setPsi().
Referenced by pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive().
void pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker ()
Definition at line 176 of file GmapFragment.java.
References pt.lsts.asa.fragments.GmapFragment.addMarkerToPos(), pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.Sys.getLatLng(), pt.lsts.asa.sys.Sys.getMaker(), pt.lsts.asa.sys.Sys.getPsi(), pt.lsts.asa.util.GmapsUtil.getRotation(), and pt.lsts.asa.fragments.GmapFragment.googleMap.
Referenced by pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive().
void pt.lsts.asa.fragments.GmapFragment.updateMyLocation (Location location)
Definition at line 150 of file GmapFragment.java.
Referenced by pt.lsts.asa.listenners.MyLocationListener.initLocationListener().
Member Data Documentation
FragmentActivity pt.lsts.asa.fragments.GmapFragment.fragmentActivity =null [private]
Definition at line 35 of file GmapFragment.java.
Referenced by pt.lsts.asa.fragments.GmapFragment.getFragmentActivity(), and pt.lsts.asa.fragments.GmapFragment.GmapFragment().
GoogleMap pt.lsts.asa.fragments.GmapFragment.googleMap = null [private]
Definition at line 37 of file GmapFragment.java.
Referenced by pt.lsts.asa.fragments.GmapFragment.getGoogleMap(), and pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
Boolean pt.lsts.asa.fragments.GmapFragment.initZoom = false [private]
Definition at line 42 of file GmapFragment.java.
MapFragment pt.lsts.asa.fragments.GmapFragment.mapFragment = null [private]
Definition at line 38 of file GmapFragment.java.
ArrayList<Marker> pt.lsts.asa.fragments.GmapFragment.markersArrayList = new ArrayList<Marker>() [private]
Definition at line 44 of file GmapFragment.java.
LatLng pt.lsts.asa.fragments.GmapFragment.myLatLng = new LatLng(0,0) [private]
Definition at line 40 of file GmapFragment.java.
Referenced by pt.lsts.asa.fragments.GmapFragment.getLastKnowLatLng().
MyLocationListener pt.lsts.asa.fragments.GmapFragment.myLocationListener = null [private]
Definition at line 41 of file GmapFragment.java.
final String pt.lsts.asa.fragments.GmapFragment.TAG = `GmapFragment` [static]
Definition at line 34 of file GmapFragment.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/fragments/GmapFragment.java