pt.lsts.asa.listenners.MyLocationListener Class Reference
Public Member Functions
MyLocationListener (final GmapFragment gmapFragment)
void initLocationListener ()
Private Attributes
LocationManager locationManager = null
GmapFragment gmapFragment = null
Detailed Description
Created by jloureiro on 1/20/15.
Definition at line 16 of file MyLocationListener.java.
Constructor & Destructor Documentation
pt.lsts.asa.listenners.MyLocationListener.MyLocationListener (final GmapFragment gmapFragment)
Definition at line 22 of file MyLocationListener.java.
References pt.lsts.asa.fragments.GmapFragment.getFragmentActivity(), and pt.lsts.asa.listenners.MyLocationListener.gmapFragment.
Member Function Documentation
void pt.lsts.asa.listenners.MyLocationListener.initLocationListener ()
Definition at line 29 of file MyLocationListener.java.
References pt.lsts.asa.fragments.GmapFragment.updateMyLocation().
Referenced by pt.lsts.asa.fragments.GmapFragment.GmapFragment().
Member Data Documentation
GmapFragment pt.lsts.asa.listenners.MyLocationListener.gmapFragment = null [private]
Definition at line 19 of file MyLocationListener.java.
Referenced by pt.lsts.asa.listenners.MyLocationListener.MyLocationListener().
LocationManager pt.lsts.asa.listenners.MyLocationListener.locationManager = null [private]
Definition at line 18 of file MyLocationListener.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/listenners/MyLocationListener.java