pt.lsts.asa.activities.SystemListActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
boolean onCreateOptionsMenu (Menu menu)
boolean onOptionsItemSelected (MenuItem item)
void loadFragments (Bundle savedInstanceState)
void onBackPressed ()
Private Attributes
SystemListFragment systemListFragment = null
SettingsButtonFragment settingsButtonFragment = null
Detailed Description
Created by jloureiro on 1/5/15.
Definition at line 17 of file SystemListActivity.java.
Member Function Documentation
void pt.lsts.asa.activities.SystemListActivity.loadFragments (Bundle savedInstanceState)
Definition at line 56 of file SystemListActivity.java.
References pt.lsts.asa.util.AndroidUtil.loadFragment().
Referenced by pt.lsts.asa.activities.SystemListActivity.onCreate().
void pt.lsts.asa.activities.SystemListActivity.onBackPressed ()
Definition at line 72 of file SystemListActivity.java.
References pt.lsts.asa.fragments.SystemListFragment.shutdown().
void pt.lsts.asa.activities.SystemListActivity.onCreate (Bundle savedInstanceState)
Definition at line 23 of file SystemListActivity.java.
References pt.lsts.asa.activities.SystemListActivity.loadFragments().
boolean pt.lsts.asa.activities.SystemListActivity.onCreateOptionsMenu (Menu menu)
Definition at line 31 of file SystemListActivity.java.
boolean pt.lsts.asa.activities.SystemListActivity.onOptionsItemSelected (MenuItem item)
Definition at line 39 of file SystemListActivity.java.
References pt.lsts.asa.fragments.SystemListFragment.populateSystemListView(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
Member Data Documentation
SettingsButtonFragment pt.lsts.asa.activities.SystemListActivity.settingsButtonFragment = null [private]
Definition at line 20 of file SystemListActivity.java.
SystemListFragment pt.lsts.asa.activities.SystemListActivity.systemListFragment = null [private]
Definition at line 19 of file SystemListActivity.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/activities/SystemListActivity.java