pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner Class Reference
Public Member Functions
CallOutPreferencesListenner (CallOut callOut)
void onPreferenceChanged (String key)
Private Attributes
final String TAG = `CallOutPreferencesListenner`
CallOut callOut = null
Detailed Description
Definition at line 15 of file CallOutPreferencesListenner.java.
Constructor & Destructor Documentation
pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.CallOutPreferencesListenner (CallOut callOut)
Definition at line 19 of file CallOutPreferencesListenner.java.
References pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.callOut.
Member Function Documentation
void pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.onPreferenceChanged (String key)
Definition at line 24 of file CallOutPreferencesListenner.java.
References pt.lsts.asa.settings.Settings.getBoolean(), pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.feedback.CallOut.setAltInterval(), pt.lsts.asa.feedback.CallOut.setAltMuteBool(), pt.lsts.asa.feedback.CallOut.setGlobalMuteBool(), pt.lsts.asa.feedback.CallOut.setIasInterval(), pt.lsts.asa.feedback.CallOut.setIasMuteBool(), pt.lsts.asa.feedback.CallOut.setSpeechRate(), pt.lsts.asa.feedback.CallOut.setTimeoutBool(), and pt.lsts.asa.feedback.CallOut.setTimeoutInterval().
Member Data Documentation
CallOut pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.callOut = null [private]
Definition at line 17 of file CallOutPreferencesListenner.java.
Referenced by pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.CallOutPreferencesListenner().
final String pt.lsts.asa.listenners.sharedPreferences.CallOutPreferencesListenner.TAG = `CallOutPreferencesListenner` [private]
Definition at line 16 of file CallOutPreferencesListenner.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/listenners/sharedPreferences/CallOutPreferencesListenner.java