pt.lsts.asa.pos.GISCoordinate Class Reference
Classes
class Ellipsoid
Public Member Functions
GISCoordinate (String lat, String latDir, String lon, String lonDir) throws Exception
GISCoordinate (double lat, double lon, boolean rad)
void setCoordinates (String lat, String latDir, String lon, String lonDir) throws Exception
double getLatInRad ()
double getLonInRad ()
double getLatInDecDeg ()
double getLonInDecDeg ()
String getLatDeg ()
String getLatMin ()
String getLatSec ()
String getLonDeg ()
String getLonMin ()
String getLonSec ()
void printDEGDEC (java.io.PrintStream ps)
void printDEGMIN (java.io.PrintStream ps)
String getPrintSeperator ()
void setPrintSeperator (String sep)
boolean getPrintLonFirst ()
void setPrintLonFirst (boolean f)
void move (double distft, double direction, int model) throws Exception
String toString ()
GISCoordinate makeClone () throws Exception
Static Public Member Functions
static GISCoordinate FromString (String s) throws Exception
static void main (String args[])
Static Public Attributes
static final int SPHERE = 0
static final int WGS84 = 1
static final int NAD27 = 2
static final int International = 3
static final int Krasovsky = 4
static final int Bessel = 5
static final int WGS72 = 6
static final int WGS66 = 7
static final int FAI_sphere = 8
static final int User = 9
static final int NAD83 = WGS84
static final int GRS80 = WGS84
Private Member Functions
void verify ()
void direct (double latRad, double lonRad, double dirRad, double distNM) throws Exception
void direct_ell (double glat1, double glon1, double faz, double s, Ellipsoid ellipse) throws Exception
double mod (double x, double y)
double modlat (double x)
double modlon (double x)
double modcrs (double x)
double parselatlon (String str) throws Exception
String degtodm (double degdec)
Private Attributes
double _lat = 0.0
double _lon = 0.0
String _sep = `,`
boolean _printLonFirst = false
Static Private Attributes
static Ellipsoid ells [] = new Ellipsoid[10]
Detailed Description
Author
Tomer Petel (tomer@pacbell.net) Credits: Calculation routines (direct() and direct_ell()) are based on work done by Ed Williams. Ed's Code is at: http://williams.best.vwh.net/gccalc.htm
Definition at line 15 of file GISCoordinate.java.
Constructor & Destructor Documentation
pt.lsts.asa.pos.GISCoordinate.GISCoordinate (String lat, String latDir, String lon, String lonDir) throws Exception
Definition at line 72 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.setCoordinates().
Referenced by pt.lsts.asa.pos.GISCoordinate.FromString(), pt.lsts.asa.pos.GISCoordinate.main(), and pt.lsts.asa.pos.GISCoordinate.makeClone().
pt.lsts.asa.pos.GISCoordinate.GISCoordinate (double lat, double lon, boolean rad)
in decimal degrees/rads if rad is true, the entered lat and lon are in radians rather than degrees. otherwise they are in degrees
Definition at line 81 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.verify().
Member Function Documentation
String pt.lsts.asa.pos.GISCoordinate.degtodm (double degdec) [private]
Definition at line 425 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.getLatDeg(), pt.lsts.asa.pos.GISCoordinate.getLatMin(), pt.lsts.asa.pos.GISCoordinate.getLatSec(), pt.lsts.asa.pos.GISCoordinate.getLonDeg(), pt.lsts.asa.pos.GISCoordinate.getLonMin(), pt.lsts.asa.pos.GISCoordinate.getLonSec(), and pt.lsts.asa.pos.GISCoordinate.printDEGMIN().
void pt.lsts.asa.pos.GISCoordinate.direct (double latRad, double lonRad, double dirRad, double distNM) throws Exception [private]
Definition at line 274 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.mod().
Referenced by pt.lsts.asa.pos.GISCoordinate.move().
void pt.lsts.asa.pos.GISCoordinate.direct_ell (double glat1, double glon1, double faz, double s, Ellipsoid ellipse) throws Exception [private]
Definition at line 299 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.modcrs(), pt.lsts.asa.pos.GISCoordinate.modlat(), and pt.lsts.asa.pos.GISCoordinate.modlon().
Referenced by pt.lsts.asa.pos.GISCoordinate.move().
static GISCoordinate pt.lsts.asa.pos.GISCoordinate.FromString (String s) throws Exception [static]
Definition at line 240 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.GISCoordinate(), and pt.lsts.asa.pos.GISCoordinate.toString().
Referenced by pt.lsts.asa.pos.GISCoordinate.main().
String pt.lsts.asa.pos.GISCoordinate.getLatDeg ()
Definition at line 119 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
double pt.lsts.asa.pos.GISCoordinate.getLatInDecDeg ()
Definition at line 110 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate._lat.
Referenced by pt.lsts.asa.util.CoordUtil.latLonAddNE2(), and pt.lsts.asa.pos.GISCoordinate.printDEGDEC().
double pt.lsts.asa.pos.GISCoordinate.getLatInRad ()
Definition at line 100 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.move().
String pt.lsts.asa.pos.GISCoordinate.getLatMin ()
Definition at line 124 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
String pt.lsts.asa.pos.GISCoordinate.getLatSec ()
Definition at line 129 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
String pt.lsts.asa.pos.GISCoordinate.getLonDeg ()
Definition at line 134 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
double pt.lsts.asa.pos.GISCoordinate.getLonInDecDeg ()
Definition at line 115 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate._lon.
Referenced by pt.lsts.asa.util.CoordUtil.latLonAddNE2(), and pt.lsts.asa.pos.GISCoordinate.printDEGDEC().
double pt.lsts.asa.pos.GISCoordinate.getLonInRad ()
Definition at line 105 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.move().
String pt.lsts.asa.pos.GISCoordinate.getLonMin ()
Definition at line 139 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
String pt.lsts.asa.pos.GISCoordinate.getLonSec ()
Definition at line 144 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
boolean pt.lsts.asa.pos.GISCoordinate.getPrintLonFirst ()
Definition at line 180 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate._printLonFirst.
Referenced by pt.lsts.asa.pos.GISCoordinate.toString().
String pt.lsts.asa.pos.GISCoordinate.getPrintSeperator ()
Definition at line 171 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate._sep.
Referenced by pt.lsts.asa.pos.GISCoordinate.toString().
static void pt.lsts.asa.pos.GISCoordinate.main (String args[]) [static]
Definition at line 437 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.FromString(), pt.lsts.asa.pos.GISCoordinate.GISCoordinate(), pt.lsts.asa.pos.GISCoordinate.move(), pt.lsts.asa.pos.GISCoordinate.printDEGDEC(), pt.lsts.asa.pos.GISCoordinate.printDEGMIN(), and pt.lsts.asa.pos.GISCoordinate.toString().
GISCoordinate pt.lsts.asa.pos.GISCoordinate.makeClone () throws Exception
Definition at line 251 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.GISCoordinate().
double pt.lsts.asa.pos.GISCoordinate.mod (double x, double y) [private]
Definition at line 367 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.direct(), pt.lsts.asa.pos.GISCoordinate.modcrs(), pt.lsts.asa.pos.GISCoordinate.modlat(), and pt.lsts.asa.pos.GISCoordinate.modlon().
double pt.lsts.asa.pos.GISCoordinate.modcrs (double x) [private]
Definition at line 379 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.mod().
Referenced by pt.lsts.asa.pos.GISCoordinate.direct_ell().
double pt.lsts.asa.pos.GISCoordinate.modlat (double x) [private]
Definition at line 371 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.mod().
Referenced by pt.lsts.asa.pos.GISCoordinate.direct_ell().
double pt.lsts.asa.pos.GISCoordinate.modlon (double x) [private]
Definition at line 375 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.mod().
Referenced by pt.lsts.asa.pos.GISCoordinate.direct_ell().
void pt.lsts.asa.pos.GISCoordinate.move (double distft, double direction, int model) throws Exception
Definition at line 193 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.direct(), pt.lsts.asa.pos.GISCoordinate.direct_ell(), pt.lsts.asa.pos.GISCoordinate.getLatInRad(), pt.lsts.asa.pos.GISCoordinate.getLonInRad(), and pt.lsts.asa.pos.GISCoordinate.Ellipsoid.name.
Referenced by pt.lsts.asa.util.CoordUtil.latLonAddNE2(), and pt.lsts.asa.pos.GISCoordinate.main().
double pt.lsts.asa.pos.GISCoordinate.parselatlon (String str) throws Exception [private]
Definition at line 383 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.setCoordinates().
void pt.lsts.asa.pos.GISCoordinate.printDEGDEC (java.io.PrintStream ps)
Definition at line 150 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.getLatInDecDeg(), and pt.lsts.asa.pos.GISCoordinate.getLonInDecDeg().
Referenced by pt.lsts.asa.pos.GISCoordinate.main().
void pt.lsts.asa.pos.GISCoordinate.printDEGMIN (java.io.PrintStream ps)
Definition at line 159 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.degtodm().
Referenced by pt.lsts.asa.pos.GISCoordinate.main(), and pt.lsts.asa.pos.GISCoordinate.toString().
void pt.lsts.asa.pos.GISCoordinate.setCoordinates (String lat, String latDir, String lon, String lonDir) throws Exception
Definition at line 92 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.parselatlon(), and pt.lsts.asa.pos.GISCoordinate.verify().
Referenced by pt.lsts.asa.pos.GISCoordinate.GISCoordinate().
void pt.lsts.asa.pos.GISCoordinate.setPrintLonFirst (boolean f)
Definition at line 184 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.toString().
void pt.lsts.asa.pos.GISCoordinate.setPrintSeperator (String sep)
Definition at line 176 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.toString().
String pt.lsts.asa.pos.GISCoordinate.toString ()
Definition at line 223 of file GISCoordinate.java.
References pt.lsts.asa.pos.GISCoordinate.getPrintLonFirst(), pt.lsts.asa.pos.GISCoordinate.getPrintSeperator(), pt.lsts.asa.pos.GISCoordinate.printDEGMIN(), pt.lsts.asa.pos.GISCoordinate.setPrintLonFirst(), and pt.lsts.asa.pos.GISCoordinate.setPrintSeperator().
Referenced by pt.lsts.asa.pos.GISCoordinate.FromString(), and pt.lsts.asa.pos.GISCoordinate.main().
void pt.lsts.asa.pos.GISCoordinate.verify () [private]
Definition at line 263 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.GISCoordinate(), and pt.lsts.asa.pos.GISCoordinate.setCoordinates().
Member Data Documentation
double pt.lsts.asa.pos.GISCoordinate._lat = 0.0 [private]
Definition at line 63 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.getLatInDecDeg().
double pt.lsts.asa.pos.GISCoordinate._lon = 0.0 [private]
Definition at line 64 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.getLonInDecDeg().
boolean pt.lsts.asa.pos.GISCoordinate._printLonFirst = false [private]
Definition at line 66 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.getPrintLonFirst().
String pt.lsts.asa.pos.GISCoordinate._sep = `,` [private]
Definition at line 65 of file GISCoordinate.java.
Referenced by pt.lsts.asa.pos.GISCoordinate.getPrintSeperator().
final int pt.lsts.asa.pos.GISCoordinate.Bessel = 5 [static]
Definition at line 21 of file GISCoordinate.java.
Ellipsoid pt.lsts.asa.pos.GISCoordinate.ells[] = new Ellipsoid[10] [static], [private]
Definition at line 43 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.FAI_sphere = 8 [static]
Definition at line 24 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.GRS80 = WGS84 [static]
Definition at line 27 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.International = 3 [static]
Definition at line 19 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.Krasovsky = 4 [static]
Definition at line 20 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.NAD27 = 2 [static]
Definition at line 18 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.NAD83 = WGS84 [static]
Definition at line 26 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.SPHERE = 0 [static]
Definition at line 16 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.User = 9 [static]
Definition at line 25 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.WGS66 = 7 [static]
Definition at line 23 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.WGS72 = 6 [static]
Definition at line 22 of file GISCoordinate.java.
final int pt.lsts.asa.pos.GISCoordinate.WGS84 = 1 [static]
Definition at line 17 of file GISCoordinate.java.
Referenced by pt.lsts.asa.util.CoordUtil.latLonAddNE2().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/pos/GISCoordinate.java