pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber Class Reference
Public Member Functions
HeartbeatVibratorIMCSubscriber (HeartbeatVibrator heartbeatVibrator)
void onReceive (final IMCMessage msg)
Static Public Attributes
static final String[] SUBSCRIBED_MSGS = { `Heartbeat` }
static final String TAG = `HeartbeatVibrator`
Private Attributes
HeartbeatVibrator heartbeatVibrator
Thread thread
Detailed Description
Definition at line 8 of file HeartbeatVibratorIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.HeartbeatVibratorIMCSubscriber (HeartbeatVibrator heartbeatVibrator)
Definition at line 15 of file HeartbeatVibratorIMCSubscriber.java.
References pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.heartbeatVibrator.
Member Function Documentation
void pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 20 of file HeartbeatVibratorIMCSubscriber.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.sys.Sys.getId(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.feedback.HeartbeatVibrator.getmDuration(), pt.lsts.asa.feedback.HeartbeatVibrator.getmVibrator(), and pt.lsts.asa.ASA.getPrefs().
Member Data Documentation
HeartbeatVibrator pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.heartbeatVibrator [private]
Definition at line 12 of file HeartbeatVibratorIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.HeartbeatVibratorIMCSubscriber().
final String [] pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.SUBSCRIBED_MSGS = { `Heartbeat` } [static]
Definition at line 10 of file HeartbeatVibratorIMCSubscriber.java.
Referenced by pt.lsts.asa.ASA.addInitialSubscribers().
final String pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.TAG = `HeartbeatVibrator` [static]
Definition at line 11 of file HeartbeatVibratorIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.thread [private]
Definition at line 13 of file HeartbeatVibratorIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/HeartbeatVibratorIMCSubscriber.java