pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber Class Reference
Public Member Functions
AccuSmsHandlerIMCSubscriber (AccuSmsHandler accuSmsHandler)
void onReceive (final IMCMessage msg)
Static Public Attributes
static final String[] SUBSCRIBED_MSGS = { `Sms` }
static final String TAG = `AccuSmsHandler`
Private Attributes
AccuSmsHandler accuSmsHandler
Thread thread
Detailed Description
Definition at line 10 of file AccuSmsHandlerIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.AccuSmsHandlerIMCSubscriber (AccuSmsHandler accuSmsHandler)
Definition at line 17 of file AccuSmsHandlerIMCSubscriber.java.
References pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.accuSmsHandler.
Member Function Documentation
void pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 22 of file AccuSmsHandlerIMCSubscriber.java.
References pt.lsts.asa.managers.IMCManager.getLocalId(), pt.lsts.asa.handlers.AccuSmsHandler.getmManager(), and pt.lsts.asa.handlers.AccuSmsHandler.sendSms().
Member Data Documentation
AccuSmsHandler pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.accuSmsHandler [private]
Definition at line 14 of file AccuSmsHandlerIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.AccuSmsHandlerIMCSubscriber().
final String [] pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.SUBSCRIBED_MSGS = { `Sms` } [static]
Definition at line 12 of file AccuSmsHandlerIMCSubscriber.java.
Referenced by pt.lsts.asa.ASA.addInitialSubscribers().
final String pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.TAG = `AccuSmsHandler` [static]
Definition at line 13 of file AccuSmsHandlerIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.AccuSmsHandlerIMCSubscriber.thread [private]
Definition at line 15 of file AccuSmsHandlerIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/AccuSmsHandlerIMCSubscriber.java