pt.lsts.asa.feedback.Heart Class Reference
Public Member Functions
Heart ()
void start ()
void stop ()
void sendHeartbeat ()
void updateVehicleList (ArrayList< Sys > list)
void onSystemListChange (ArrayList< Sys > list)
Static Public Attributes
static final boolean DEBUG = false
static final String TAG = `Heart`
Detailed Description
Definition at line 14 of file Heart.java.
Constructor & Destructor Documentation
pt.lsts.asa.feedback.Heart.Heart ()
Definition at line 30 of file Heart.java.
Member Function Documentation
void pt.lsts.asa.feedback.Heart.onSystemListChange (ArrayList< Sys > list)
Implements pt.lsts.asa.listenners.SystemListChangeListener.
Definition at line 61 of file Heart.java.
References pt.lsts.asa.feedback.Heart.updateVehicleList().
void pt.lsts.asa.feedback.Heart.sendHeartbeat ()
Definition at line 43 of file Heart.java.
References pt.lsts.asa.managers.IMCManager.sendToSys().
void pt.lsts.asa.feedback.Heart.start ()
Definition at line 35 of file Heart.java.
References pt.lsts.asa.util.AccuTimer.start().
Referenced by pt.lsts.asa.ASA.start().
void pt.lsts.asa.feedback.Heart.stop ()
Definition at line 39 of file Heart.java.
References pt.lsts.asa.util.AccuTimer.stop().
Referenced by pt.lsts.asa.ASA.pause().
void pt.lsts.asa.feedback.Heart.updateVehicleList (ArrayList< Sys > list)
Definition at line 52 of file Heart.java.
Referenced by pt.lsts.asa.feedback.Heart.onSystemListChange().
Member Data Documentation
final boolean pt.lsts.asa.feedback.Heart.DEBUG = false [static]
Definition at line 15 of file Heart.java.
final String pt.lsts.asa.feedback.Heart.TAG = `Heart` [static]
Definition at line 16 of file Heart.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/feedback/Heart.java