pt.lsts.asa.subscribers.CallOutIMCSubscriber Class Reference
Public Member Functions
CallOutIMCSubscriber (CallOut callOut)
void onReceive (final IMCMessage msg)
Private Attributes
final String TAG = `CallOutIMCSubscriber`
Thread thread
CallOut callOut
Detailed Description
Definition at line 18 of file CallOutIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.CallOutIMCSubscriber.CallOutIMCSubscriber (CallOut callOut)
Definition at line 24 of file CallOutIMCSubscriber.java.
References pt.lsts.asa.subscribers.CallOutIMCSubscriber.callOut.
Member Function Documentation
void pt.lsts.asa.subscribers.CallOutIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 29 of file CallOutIMCSubscriber.java.
References pt.lsts.asa.util.IMCUtils.isMsgFromActive(), pt.lsts.asa.feedback.CallOut.setAltValue(), pt.lsts.asa.feedback.CallOut.setIasValue(), and pt.lsts.asa.feedback.CallOut.setLastMsgReceived().
Member Data Documentation
CallOut pt.lsts.asa.subscribers.CallOutIMCSubscriber.callOut [private]
Definition at line 22 of file CallOutIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.CallOutIMCSubscriber.CallOutIMCSubscriber().
final String pt.lsts.asa.subscribers.CallOutIMCSubscriber.TAG = `CallOutIMCSubscriber` [private]
Definition at line 20 of file CallOutIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.CallOutIMCSubscriber.thread [private]
Definition at line 21 of file CallOutIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/CallOutIMCSubscriber.java