pt.lsts.asa.fragments.VideoViewFragment Class Reference
Public Member Functions
VideoViewFragment ()
VideoViewFragment (FragmentActivity fragmentActivity)
void onCreate (Bundle savedInstanceState)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onAttach (Activity activity)
void onDetach ()
void onStart ()
void onResume ()
void setVideoViewListeners ()
void startVideo ()
void restartVideo ()
void setConnectionChecker ()
void setRunnable ()
void startHandle (int timeout)
Private Attributes
final String TAG = `VideoView`
FragmentActivity fragmentActivity
VideoView videoView
ScheduledFuture handle
final ScheduledExecutorService scheduler
final int timeoutFalse =5000
boolean connectedBool =false
Detailed Description
Definition at line 25 of file VideoViewFragment.java.
Constructor & Destructor Documentation
pt.lsts.asa.fragments.VideoViewFragment.VideoViewFragment ()
Definition at line 38 of file VideoViewFragment.java.
pt.lsts.asa.fragments.VideoViewFragment.VideoViewFragment (FragmentActivity fragmentActivity)
Definition at line 42 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.fragmentActivity.
Member Function Documentation
void pt.lsts.asa.fragments.VideoViewFragment.onAttach (Activity activity)
Definition at line 62 of file VideoViewFragment.java.
void pt.lsts.asa.fragments.VideoViewFragment.onCreate (Bundle savedInstanceState)
Definition at line 47 of file VideoViewFragment.java.
View pt.lsts.asa.fragments.VideoViewFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 52 of file VideoViewFragment.java.
void pt.lsts.asa.fragments.VideoViewFragment.onDetach ()
Definition at line 67 of file VideoViewFragment.java.
void pt.lsts.asa.fragments.VideoViewFragment.onResume ()
Definition at line 78 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.setConnectionChecker(), and pt.lsts.asa.fragments.VideoViewFragment.startVideo().
void pt.lsts.asa.fragments.VideoViewFragment.onStart ()
Definition at line 72 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.setVideoViewListeners().
void pt.lsts.asa.fragments.VideoViewFragment.restartVideo ()
Definition at line 117 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.startVideo().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.setRunnable(), and pt.lsts.asa.fragments.VideoViewFragment.setVideoViewListeners().
void pt.lsts.asa.fragments.VideoViewFragment.setConnectionChecker ()
Definition at line 123 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.setRunnable(), and pt.lsts.asa.fragments.VideoViewFragment.startHandle().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.onResume().
void pt.lsts.asa.fragments.VideoViewFragment.setRunnable ()
Definition at line 128 of file VideoViewFragment.java.
References pt.lsts.asa.fragments.VideoViewFragment.restartVideo(), pt.lsts.asa.util.AndroidUtil.showToastLong(), pt.lsts.asa.util.AndroidUtil.showToastShort(), and pt.lsts.asa.fragments.VideoViewFragment.startHandle().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.setConnectionChecker().
void pt.lsts.asa.fragments.VideoViewFragment.setVideoViewListeners ()
Definition at line 84 of file VideoViewFragment.java.
References pt.lsts.asa.util.StringUtils.getCamUrl(), pt.lsts.asa.fragments.VideoViewFragment.restartVideo(), and pt.lsts.asa.util.AndroidUtil.showToastShort().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.onStart().
void pt.lsts.asa.fragments.VideoViewFragment.startHandle (int timeout)
Definition at line 153 of file VideoViewFragment.java.
Referenced by pt.lsts.asa.fragments.VideoViewFragment.setConnectionChecker(), and pt.lsts.asa.fragments.VideoViewFragment.setRunnable().
void pt.lsts.asa.fragments.VideoViewFragment.startVideo ()
Definition at line 105 of file VideoViewFragment.java.
References pt.lsts.asa.util.StringUtils.getCamUrl().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.onResume(), and pt.lsts.asa.fragments.VideoViewFragment.restartVideo().
Member Data Documentation
boolean pt.lsts.asa.fragments.VideoViewFragment.connectedBool =false [private]
Definition at line 36 of file VideoViewFragment.java.
FragmentActivity pt.lsts.asa.fragments.VideoViewFragment.fragmentActivity [private]
Definition at line 28 of file VideoViewFragment.java.
Referenced by pt.lsts.asa.fragments.VideoViewFragment.VideoViewFragment().
ScheduledFuture pt.lsts.asa.fragments.VideoViewFragment.handle [private]
Definition at line 31 of file VideoViewFragment.java.
final ScheduledExecutorService pt.lsts.asa.fragments.VideoViewFragment.scheduler [private]
Initial value:
= Executors
            .newScheduledThreadPool(1)
Definition at line 32 of file VideoViewFragment.java.
final String pt.lsts.asa.fragments.VideoViewFragment.TAG = `VideoView` [private]
Definition at line 27 of file VideoViewFragment.java.
final int pt.lsts.asa.fragments.VideoViewFragment.timeoutFalse =5000 [private]
Definition at line 35 of file VideoViewFragment.java.
VideoView pt.lsts.asa.fragments.VideoViewFragment.videoView [private]
Definition at line 29 of file VideoViewFragment.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/fragments/VideoViewFragment.java