pt.lsts.asa.settings.SettingsFactory Class Reference
Static Public Member Functions
static void populate (PreferenceCategory category, Context context)
static void createHideEntry (final PreferenceCategory category, final Context context)
static void hideCategory (final PreferenceCategory category, final Context context)
static EditTextPreference createEntry (PreferenceCategory category, String key, String valString, Context context)
static EditTextPreference createEntry (PreferenceCategory category, String key, Integer valInteger, Context context)
static ListPreference createEntry (PreferenceCategory category, String key, String defValue, String[] list, Context context)
static void setOnChangeListenerList (final ListPreference listPreference, final String key)
static void setOnChangeListener (final EditTextPreference editTextPreference, final String key)
static void createEntry (PreferenceCategory category, final String key, Boolean val, Context context)
static boolean changeValue (String key, Object newValue)
static PreferenceCategory createCategory (String name, final Context context)
static Vector< PreferenceCategory > fetchCategories (Context context)
static Vector< Preference > fetchPreferencesButtons (final Context context)
static Preference createSaveButton (final Context context)
static Preference createLoadButton (final Context context)
static Preference createRestoreButton (final Context context)
static void restoreDefaults (final Context context)
static void load (final Context context)
static void save (final Context context)
static void regenerateActivity (Context context)
Detailed Description
Definition at line 24 of file SettingsFactory.java.
Member Function Documentation
static boolean pt.lsts.asa.settings.SettingsFactory.changeValue (String key, Object newValue) [static]
Definition at line 187 of file SettingsFactory.java.
References pt.lsts.asa.settings.Settings.getSharedPreferences(), pt.lsts.asa.settings.Settings.putBoolean(), pt.lsts.asa.settings.Settings.putInt(), and pt.lsts.asa.settings.Settings.putString().
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry(), pt.lsts.asa.settings.SettingsFactory.setOnChangeListener(), and pt.lsts.asa.settings.SettingsFactory.setOnChangeListenerList().
static PreferenceCategory pt.lsts.asa.settings.SettingsFactory.createCategory (String name, final Context context) [static]
Definition at line 202 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.populate().
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchCategories().
static EditTextPreference pt.lsts.asa.settings.SettingsFactory.createEntry (PreferenceCategory category, String key, String valString, Context context) [static]
Definition at line 98 of file SettingsFactory.java.
References pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getKey(), pt.lsts.asa.settings.Settings.getString(), and pt.lsts.asa.settings.SettingsFactory.setOnChangeListener().
Referenced by pt.lsts.asa.settings.SettingsFactory.populate().
static EditTextPreference pt.lsts.asa.settings.SettingsFactory.createEntry (PreferenceCategory category, String key, Integer valInteger, Context context) [static]
Definition at line 109 of file SettingsFactory.java.
References pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getKey(), and pt.lsts.asa.settings.SettingsFactory.setOnChangeListener().
static ListPreference pt.lsts.asa.settings.SettingsFactory.createEntry (PreferenceCategory category, String key, String defValue, String[] list, Context context) [static]
Definition at line 123 of file SettingsFactory.java.
References pt.lsts.asa.settings.Settings.getDescription(), pt.lsts.asa.settings.Settings.getKey(), and pt.lsts.asa.settings.SettingsFactory.setOnChangeListenerList().
static void pt.lsts.asa.settings.SettingsFactory.createEntry (PreferenceCategory category, final String key, Boolean val, Context context) [static]
Definition at line 164 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.changeValue(), pt.lsts.asa.settings.Settings.getDescription(), and pt.lsts.asa.settings.Settings.getKey().
static void pt.lsts.asa.settings.SettingsFactory.createHideEntry (final PreferenceCategory category, final Context context) [static]
Definition at line 61 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.hideCategory().
Referenced by pt.lsts.asa.settings.SettingsFactory.populate().
static Preference pt.lsts.asa.settings.SettingsFactory.createLoadButton (final Context context) [static]
Definition at line 261 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.load().
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchPreferencesButtons().
static Preference pt.lsts.asa.settings.SettingsFactory.createRestoreButton (final Context context) [static]
Definition at line 275 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.restoreDefaults().
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchPreferencesButtons().
static Preference pt.lsts.asa.settings.SettingsFactory.createSaveButton (final Context context) [static]
Definition at line 247 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.save().
Referenced by pt.lsts.asa.settings.SettingsFactory.fetchPreferencesButtons().
static Vector<PreferenceCategory> pt.lsts.asa.settings.SettingsFactory.fetchCategories (Context context) [static]
Definition at line 219 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.createCategory(), pt.lsts.asa.settings.Settings.getAll(), and pt.lsts.asa.settings.Settings.getCategory().
Referenced by pt.lsts.asa.activities.SettingsActivity.onCreate().
static Vector<Preference> pt.lsts.asa.settings.SettingsFactory.fetchPreferencesButtons (final Context context) [static]
Definition at line 237 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.createLoadButton(), pt.lsts.asa.settings.SettingsFactory.createRestoreButton(), and pt.lsts.asa.settings.SettingsFactory.createSaveButton().
Referenced by pt.lsts.asa.activities.SettingsActivity.createProfileCategory().
static void pt.lsts.asa.settings.SettingsFactory.hideCategory (final PreferenceCategory category, final Context context) [static]
Definition at line 78 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.populate().
Referenced by pt.lsts.asa.settings.SettingsFactory.createHideEntry().
static void pt.lsts.asa.settings.SettingsFactory.load (final Context context) [static]
Definition at line 311 of file SettingsFactory.java.
References pt.lsts.asa.settings.Profile.getProfilesAvailable(), pt.lsts.asa.settings.Profile.load(), and pt.lsts.asa.settings.SettingsFactory.regenerateActivity().
Referenced by pt.lsts.asa.settings.SettingsFactory.createLoadButton().
static void pt.lsts.asa.settings.SettingsFactory.populate (PreferenceCategory category, Context context) [static]
Definition at line 26 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.createEntry(), pt.lsts.asa.settings.SettingsFactory.createHideEntry(), pt.lsts.asa.settings.Settings.getAll(), pt.lsts.asa.settings.Settings.getBoolean(), pt.lsts.asa.settings.Settings.getCategory(), pt.lsts.asa.settings.Settings.getInt(), pt.lsts.asa.settings.Settings.getOptions(), pt.lsts.asa.settings.Settings.getString(), pt.lsts.asa.settings.Settings.getType(), pt.lsts.asa.settings.Settings.hasOptions(), and pt.lsts.asa.settings.Settings.isOptions().
Referenced by pt.lsts.asa.settings.SettingsFactory.createCategory(), pt.lsts.asa.settings.SettingsFactory.hideCategory(), and pt.lsts.asa.activities.SettingsActivity.populateCategories().
static void pt.lsts.asa.settings.SettingsFactory.regenerateActivity (Context context) [static]
Definition at line 347 of file SettingsFactory.java.
Referenced by pt.lsts.asa.settings.SettingsFactory.load(), and pt.lsts.asa.settings.SettingsFactory.restoreDefaults().
static void pt.lsts.asa.settings.SettingsFactory.restoreDefaults (final Context context) [static]
Definition at line 289 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.regenerateActivity(), and pt.lsts.asa.settings.Profile.restoreDefaults().
Referenced by pt.lsts.asa.settings.SettingsFactory.createRestoreButton().
static void pt.lsts.asa.settings.SettingsFactory.save (final Context context) [static]
Definition at line 324 of file SettingsFactory.java.
References pt.lsts.asa.settings.Profile.save().
Referenced by pt.lsts.asa.settings.SettingsFactory.createSaveButton().
static void pt.lsts.asa.settings.SettingsFactory.setOnChangeListener (final EditTextPreference editTextPreference, final String key) [static]
Definition at line 148 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.changeValue(), and pt.lsts.asa.settings.Settings.getDescription().
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry().
static void pt.lsts.asa.settings.SettingsFactory.setOnChangeListenerList (final ListPreference listPreference, final String key) [static]
Definition at line 135 of file SettingsFactory.java.
References pt.lsts.asa.settings.SettingsFactory.changeValue(), and pt.lsts.asa.settings.Settings.getDescription().
Referenced by pt.lsts.asa.settings.SettingsFactory.createEntry().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/settings/SettingsFactory.java