pt.lsts.asa.util.AccuTimer Class Reference
Public Member Functions
AccuTimer (Runnable runnable, long delay)
void start ()
void stop ()
void setDelay (long delay)
Detailed Description
Helper class that implements a regular simple Timer for one runnable
Author
sharp
Definition at line 12 of file AccuTimer.java.
Constructor & Destructor Documentation
pt.lsts.asa.util.AccuTimer.AccuTimer (Runnable runnable, long delay)
Definition at line 27 of file AccuTimer.java.
Member Function Documentation
void pt.lsts.asa.util.AccuTimer.setDelay (long delay)
Definition at line 41 of file AccuTimer.java.
void pt.lsts.asa.util.AccuTimer.start ()
Definition at line 32 of file AccuTimer.java.
Referenced by pt.lsts.asa.feedback.Heart.start(), and pt.lsts.asa.comms.Announcer.start().
void pt.lsts.asa.util.AccuTimer.stop ()
Definition at line 37 of file AccuTimer.java.
Referenced by pt.lsts.asa.feedback.Heart.stop(), and pt.lsts.asa.comms.Announcer.stop().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/AccuTimer.java