pt.lsts.asa.managers.GPSManager Class Reference
Public Member Functions
GPSManager (Context context)
void addListener (LocationChangeListener l)
void removeListener (LocationChangeListener l)
Location getCurrentLocation ()
void start ()
void stop ()
Static Public Attributes
static final String TAG = `GPSManager`
Private Member Functions
void updateLocation ()
Private Attributes
ArrayList< LocationChangeListener > listeners = new ArrayList<LocationChangeListener>()
Location currentLocation = new Location(`gps`)
Detailed Description
Simple GPS manager that only deals with location changes and routes the info to a series of listeners in a list. If there is no listener it auto-shutdown the GPS locator
Author
sharp
Definition at line 23 of file GPSManager.java.
Constructor & Destructor Documentation
pt.lsts.asa.managers.GPSManager.GPSManager (Context context)
Definition at line 55 of file GPSManager.java.
Member Function Documentation
void pt.lsts.asa.managers.GPSManager.addListener (LocationChangeListener l)
Definition at line 60 of file GPSManager.java.
References pt.lsts.asa.managers.GPSManager.start(), and pt.lsts.asa.managers.GPSManager.updateLocation().
Referenced by pt.lsts.asa.comms.Announcer.start().
Location pt.lsts.asa.managers.GPSManager.getCurrentLocation ()
Definition at line 91 of file GPSManager.java.
References pt.lsts.asa.managers.GPSManager.currentLocation.
Referenced by pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce().
void pt.lsts.asa.managers.GPSManager.removeListener (LocationChangeListener l)
Definition at line 73 of file GPSManager.java.
References pt.lsts.asa.managers.GPSManager.stop().
Referenced by pt.lsts.asa.comms.Announcer.stop().
void pt.lsts.asa.managers.GPSManager.start ()
Definition at line 95 of file GPSManager.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.getPrefs().
Referenced by pt.lsts.asa.managers.GPSManager.addListener().
void pt.lsts.asa.managers.GPSManager.stop ()
Definition at line 108 of file GPSManager.java.
Referenced by pt.lsts.asa.managers.GPSManager.removeListener().
void pt.lsts.asa.managers.GPSManager.updateLocation () [private]
Definition at line 85 of file GPSManager.java.
Referenced by pt.lsts.asa.managers.GPSManager.addListener().
Member Data Documentation
Location pt.lsts.asa.managers.GPSManager.currentLocation = new Location(`gps`) [private]
Definition at line 27 of file GPSManager.java.
Referenced by pt.lsts.asa.managers.GPSManager.getCurrentLocation().
ArrayList<LocationChangeListener> pt.lsts.asa.managers.GPSManager.listeners = new ArrayList<LocationChangeListener>() [private]
Definition at line 26 of file GPSManager.java.
final String pt.lsts.asa.managers.GPSManager.TAG = `GPSManager` [static]
Definition at line 24 of file GPSManager.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/managers/GPSManager.java