pt.lsts.asa.fragments.SoundControlFragment Class Reference
Public Member Functions
SoundControlFragment ()
SoundControlFragment (FragmentActivity fragmentActivity)
void onCreate (Bundle savedInstanceState)
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
void onAttach (Activity activity)
void onDetach ()
void onStart ()
void setVolumeControl ()
void setImageButtonMute ()
void setImageButtonMuteIcon ()
void setVolumeControlChanger (VerticalSeekBar volControl, final AudioManager audioManager)
void mute ()
void unmute ()
void shutdown ()
Private Member Functions
void adjustVolumeBarAndIcon ()
Detailed Description
Definition at line 19 of file SoundControlFragment.java.
Constructor & Destructor Documentation
pt.lsts.asa.fragments.SoundControlFragment.SoundControlFragment ()
Definition at line 27 of file SoundControlFragment.java.
pt.lsts.asa.fragments.SoundControlFragment.SoundControlFragment (FragmentActivity fragmentActivity)
Definition at line 31 of file SoundControlFragment.java.
Member Function Documentation
void pt.lsts.asa.fragments.SoundControlFragment.adjustVolumeBarAndIcon () [private]
Definition at line 122 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.getCurrentVolume(), and pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setVolumeControlChanger().
void pt.lsts.asa.fragments.SoundControlFragment.mute ()
Definition at line 128 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.mute(), and pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute().
void pt.lsts.asa.fragments.SoundControlFragment.onAttach (Activity activity)
Definition at line 52 of file SoundControlFragment.java.
void pt.lsts.asa.fragments.SoundControlFragment.onCreate (Bundle savedInstanceState)
Definition at line 36 of file SoundControlFragment.java.
View pt.lsts.asa.fragments.SoundControlFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Definition at line 41 of file SoundControlFragment.java.
void pt.lsts.asa.fragments.SoundControlFragment.onDetach ()
Definition at line 57 of file SoundControlFragment.java.
void pt.lsts.asa.fragments.SoundControlFragment.onStart ()
Definition at line 62 of file SoundControlFragment.java.
References pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl().
void pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute ()
Definition at line 78 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.checkMute(), pt.lsts.asa.fragments.SoundControlFragment.mute(), pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl().
void pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon ()
Definition at line 92 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.checkMute().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.adjustVolumeBarAndIcon(), pt.lsts.asa.fragments.SoundControlFragment.mute(), pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
void pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl ()
Definition at line 68 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.getCurrentVolume(), pt.lsts.asa.managers.SoundManager.getMaxVolume(), pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute(), and pt.lsts.asa.fragments.SoundControlFragment.setVolumeControlChanger().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.onStart().
void pt.lsts.asa.fragments.SoundControlFragment.setVolumeControlChanger (VerticalSeekBar volControl, final AudioManager audioManager)
Definition at line 99 of file SoundControlFragment.java.
References pt.lsts.asa.fragments.SoundControlFragment.adjustVolumeBarAndIcon(), pt.lsts.asa.managers.SoundManager.setCurrentVolume(), and pt.lsts.asa.fragments.SoundControlFragment.unmute().
Referenced by pt.lsts.asa.fragments.SoundControlFragment.setVolumeControl().
void pt.lsts.asa.fragments.SoundControlFragment.shutdown ()
Definition at line 139 of file SoundControlFragment.java.
References pt.lsts.asa.fragments.SoundControlFragment.unmute().
Referenced by pt.lsts.asa.activities.ManualActivity.back().
void pt.lsts.asa.fragments.SoundControlFragment.unmute ()
Definition at line 133 of file SoundControlFragment.java.
References pt.lsts.asa.managers.SoundManager.getCurrentVolume(), pt.lsts.asa.managers.SoundManager.setCurrentVolume(), pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMuteIcon(), and pt.lsts.asa.managers.SoundManager.unmute().
Referenced by pt.lsts.asa.activities.ManualActivity.onPostCreate(), pt.lsts.asa.fragments.SoundControlFragment.setImageButtonMute(), pt.lsts.asa.fragments.SoundControlFragment.setVolumeControlChanger(), and pt.lsts.asa.fragments.SoundControlFragment.shutdown().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/fragments/SoundControlFragment.java