pt.lsts.asa.feedback.HeartbeatVibrator Class Reference
Public Member Functions
HeartbeatVibrator (Context context, IMCManager imm)
HeartbeatVibrator (Context context, IMCManager imm, int duration)
int getmDuration ()
void setmDuration (int mDuration)
void setmVibrator (Vibrator mVibrator)
Vibrator getmVibrator ()
Static Public Attributes
static final int DEFAULT_DURATION = 50
Private Attributes
Vibrator mVibrator
int mDuration
IMCManager imm
Detailed Description
Simple class that vibrates on receiving an heartbeat message Should be added as a listener to `heartbeat` message
Author
jqcorreia
Definition at line 15 of file HeartbeatVibrator.java.
Constructor & Destructor Documentation
pt.lsts.asa.feedback.HeartbeatVibrator.HeartbeatVibrator (Context context, IMCManager imm)
Definition at line 22 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.imm, and pt.lsts.asa.feedback.HeartbeatVibrator.setmDuration().
pt.lsts.asa.feedback.HeartbeatVibrator.HeartbeatVibrator (Context context, IMCManager imm, int duration)
Definition at line 29 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.imm, and pt.lsts.asa.feedback.HeartbeatVibrator.setmDuration().
Member Function Documentation
int pt.lsts.asa.feedback.HeartbeatVibrator.getmDuration ()
Definition at line 34 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.mDuration.
Referenced by pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive().
Vibrator pt.lsts.asa.feedback.HeartbeatVibrator.getmVibrator ()
Definition at line 46 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.mVibrator.
Referenced by pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive().
void pt.lsts.asa.feedback.HeartbeatVibrator.setmDuration (int mDuration)
Definition at line 38 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.mDuration.
Referenced by pt.lsts.asa.feedback.HeartbeatVibrator.HeartbeatVibrator().
void pt.lsts.asa.feedback.HeartbeatVibrator.setmVibrator (Vibrator mVibrator)
Definition at line 42 of file HeartbeatVibrator.java.
References pt.lsts.asa.feedback.HeartbeatVibrator.mVibrator.
Member Data Documentation
final int pt.lsts.asa.feedback.HeartbeatVibrator.DEFAULT_DURATION = 50 [static]
Definition at line 20 of file HeartbeatVibrator.java.
IMCManager pt.lsts.asa.feedback.HeartbeatVibrator.imm [private]
Definition at line 19 of file HeartbeatVibrator.java.
Referenced by pt.lsts.asa.feedback.HeartbeatVibrator.HeartbeatVibrator().
int pt.lsts.asa.feedback.HeartbeatVibrator.mDuration [private]
Definition at line 18 of file HeartbeatVibrator.java.
Referenced by pt.lsts.asa.feedback.HeartbeatVibrator.getmDuration(), and pt.lsts.asa.feedback.HeartbeatVibrator.setmDuration().
Vibrator pt.lsts.asa.feedback.HeartbeatVibrator.mVibrator [private]
Definition at line 17 of file HeartbeatVibrator.java.
Referenced by pt.lsts.asa.feedback.HeartbeatVibrator.getmVibrator(), and pt.lsts.asa.feedback.HeartbeatVibrator.setmVibrator().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/feedback/HeartbeatVibrator.java