pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber Class Reference
Public Member Functions
ManualIndicatorsFragmentIMCSubscriber (ManualIndicatorsFragment manualIndicatorsfragment)
void onReceive (final IMCMessage msg)
Private Attributes
final String TAG = `ManualIndicatorsFragmentIMCSubscriber`
ManualIndicatorsFragment manualIndicatorsfragment = null
Thread thread
NumberFormat formatter = new DecimalFormat(`#0`)
Detailed Description
Created by jloureiro on 1/21/15.
Definition at line 19 of file ManualIndicatorsFragmentIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.ManualIndicatorsFragmentIMCSubscriber (ManualIndicatorsFragment manualIndicatorsfragment)
Definition at line 27 of file ManualIndicatorsFragmentIMCSubscriber.java.
References pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.manualIndicatorsfragment.
Member Function Documentation
void pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 32 of file ManualIndicatorsFragmentIMCSubscriber.java.
References pt.lsts.asa.util.IMCUtils.isMsgFromActive(), pt.lsts.asa.fragments.ManualIndicatorsFragment.setLeftTextView(), pt.lsts.asa.fragments.ManualIndicatorsFragment.setRightTextView(), and pt.lsts.asa.fragments.ManualIndicatorsFragment.startScheduler().
Member Data Documentation
NumberFormat pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.formatter = new DecimalFormat(`#0`) [private]
Definition at line 25 of file ManualIndicatorsFragmentIMCSubscriber.java.
ManualIndicatorsFragment pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.manualIndicatorsfragment = null [private]
Definition at line 22 of file ManualIndicatorsFragmentIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.ManualIndicatorsFragmentIMCSubscriber().
final String pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.TAG = `ManualIndicatorsFragmentIMCSubscriber` [private]
Definition at line 21 of file ManualIndicatorsFragmentIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.thread [private]
Definition at line 23 of file ManualIndicatorsFragmentIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/ManualIndicatorsFragmentIMCSubscriber.java