pt.lsts.asa.util.IMCUtils Class Reference
Static Public Member Functions
static ArrayList< String > getAnnounceService (IMCMessage msg, String service)
static String[] getAnnounceIMCAddressPort (IMCMessage msg)
static boolean isMsgFromActive (IMCMessage msg)
Detailed Description
Definition at line 11 of file IMCUtils.java.
Member Function Documentation
static String [] pt.lsts.asa.util.IMCUtils.getAnnounceIMCAddressPort (IMCMessage msg) [static]
Parameters
msg IMCMessage containing the Announce to extract the address from.
Returns
The node address for IMC communications.
Definition at line 43 of file IMCUtils.java.
References pt.lsts.asa.util.IMCUtils.getAnnounceService().
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
static ArrayList<String> pt.lsts.asa.util.IMCUtils.getAnnounceService (IMCMessage msg, String service) [static]
This function return the full address on a service specified in the Announce message of a node
Parameters
msg the message to be inspected
service The name of the service to be looked for
Returns
Returns a string like <address:port>, null if msg not an announce or service doesnt exist.
Definition at line 23 of file IMCUtils.java.
Referenced by pt.lsts.asa.util.IMCUtils.getAnnounceIMCAddressPort(), and pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
static boolean pt.lsts.asa.util.IMCUtils.isMsgFromActive (IMCMessage msg) [static]
Definition at line 65 of file IMCUtils.java.
References pt.lsts.asa.ASA.getActiveSys(), pt.lsts.asa.sys.Sys.getId(), and pt.lsts.asa.ASA.getInstance().
Referenced by pt.lsts.asa.subscribers.CallOutIMCSubscriber.onReceive(), pt.lsts.asa.subscribers.GmapIMCSubscriber.onReceive(), and pt.lsts.asa.subscribers.ManualIndicatorsFragmentIMCSubscriber.onReceive().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/IMCUtils.java