pt.lsts.asa.subscribers.SystemListIMCSubscriber Class Reference
Public Member Functions
SystemListIMCSubscriber (SystemList systemList)
void onReceive (final IMCMessage msg)
Static Public Attributes
static final String TAG = `SystemList`
static final int CONNECTED_TIME_LIMIT = 5000
static final boolean DEBUG = false
Private Attributes
SystemList systemList
Thread thread
Detailed Description
Definition at line 16 of file SystemListIMCSubscriber.java.
Constructor & Destructor Documentation
pt.lsts.asa.subscribers.SystemListIMCSubscriber.SystemListIMCSubscriber (SystemList systemList)
Definition at line 24 of file SystemListIMCSubscriber.java.
References pt.lsts.asa.subscribers.SystemListIMCSubscriber.systemList.
Member Function Documentation
void pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive (final IMCMessage msg)
Definition at line 30 of file SystemListIMCSubscriber.java.
References pt.lsts.asa.sys.SystemList.changeList(), pt.lsts.asa.sys.SystemList.containsSysName(), pt.lsts.asa.sys.SystemList.findSysById(), pt.lsts.asa.sys.SystemList.findSysByName(), pt.lsts.asa.sys.Sys.getAddress(), pt.lsts.asa.util.IMCUtils.getAnnounceIMCAddressPort(), pt.lsts.asa.util.IMCUtils.getAnnounceService(), pt.lsts.asa.managers.IMCManager.getComm(), pt.lsts.asa.ASA.getIMCManager(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.sys.SystemList.getList(), pt.lsts.asa.sys.Sys.getName(), pt.lsts.asa.sys.Sys.getPort(), pt.lsts.asa.sys.Sys.isConnected(), pt.lsts.asa.sys.Sys.lastMessageReceived, pt.lsts.asa.managers.IMCManager.send(), and pt.lsts.asa.sys.Sys.setError().
Member Data Documentation
final int pt.lsts.asa.subscribers.SystemListIMCSubscriber.CONNECTED_TIME_LIMIT = 5000 [static]
Definition at line 19 of file SystemListIMCSubscriber.java.
final boolean pt.lsts.asa.subscribers.SystemListIMCSubscriber.DEBUG = false [static]
Definition at line 20 of file SystemListIMCSubscriber.java.
SystemList pt.lsts.asa.subscribers.SystemListIMCSubscriber.systemList [private]
Definition at line 21 of file SystemListIMCSubscriber.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.SystemListIMCSubscriber().
final String pt.lsts.asa.subscribers.SystemListIMCSubscriber.TAG = `SystemList` [static]
Definition at line 18 of file SystemListIMCSubscriber.java.
Thread pt.lsts.asa.subscribers.SystemListIMCSubscriber.thread [private]
Definition at line 22 of file SystemListIMCSubscriber.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/subscribers/SystemListIMCSubscriber.java