pt.lsts.asa.pos.LblBeaconList Class Reference
Public Member Functions
LblBeaconList ()
void notifyListeners ()
ArrayList< Beacon > getList ()
ArrayList< String > getNameList ()
Beacon getBeaconByName (String name)
void addBeaconListChangeListener (BeaconListChangeListener l)
Static Public Attributes
static final String[] SUBSCRIBED_MSGS = { `LblConfig` }
static final String TAG = `LblBeaconList`
Private Attributes
ArrayList< Beacon > list = new ArrayList<Beacon>()
Detailed Description
Definition at line 8 of file LblBeaconList.java.
Constructor & Destructor Documentation
pt.lsts.asa.pos.LblBeaconList.LblBeaconList ()
Definition at line 16 of file LblBeaconList.java.
Member Function Documentation
void pt.lsts.asa.pos.LblBeaconList.addBeaconListChangeListener (BeaconListChangeListener l)
Definition at line 47 of file LblBeaconList.java.
Beacon pt.lsts.asa.pos.LblBeaconList.getBeaconByName (String name)
Definition at line 39 of file LblBeaconList.java.
ArrayList<Beacon> pt.lsts.asa.pos.LblBeaconList.getList ()
Definition at line 26 of file LblBeaconList.java.
References pt.lsts.asa.pos.LblBeaconList.list.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive().
ArrayList<String> pt.lsts.asa.pos.LblBeaconList.getNameList ()
Definition at line 30 of file LblBeaconList.java.
void pt.lsts.asa.pos.LblBeaconList.notifyListeners ()
Definition at line 20 of file LblBeaconList.java.
Referenced by pt.lsts.asa.subscribers.LblBeaconListIMCSubscriber.onReceive().
Member Data Documentation
ArrayList<Beacon> pt.lsts.asa.pos.LblBeaconList.list = new ArrayList<Beacon>() [private]
Definition at line 11 of file LblBeaconList.java.
Referenced by pt.lsts.asa.pos.LblBeaconList.getList().
final String [] pt.lsts.asa.pos.LblBeaconList.SUBSCRIBED_MSGS = { `LblConfig` } [static]
Definition at line 9 of file LblBeaconList.java.
final String pt.lsts.asa.pos.LblBeaconList.TAG = `LblBeaconList` [static]
Definition at line 10 of file LblBeaconList.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/pos/LblBeaconList.java