pt.lsts.asa.comms.Announcer Class Reference
Public Member Functions
Announcer (IMCManager imm, String broadcast, String multicast)
void start ()
void stop ()
void setBroadcastAddress (String addr)
void generateAnnounce ()
Static Public Attributes
static final String TAG = `Announcer`
static final String ANNOUNCE_ADDR = `224.0.75.69`
static final int ANNOUNCE_PORT = 30100
static final long ANNOUNCE_DELAY = 10000
static final boolean DEBUG = false
Private Member Functions
void updateLocationOnAnnounce ()
void updateHeadingOnAnnounce ()
Private Attributes
IMCMessage announce
IMCManager imm
String broadcastAddress
String multicastAddress
AccuTimer at
int gpsAddListenerCounter = 0
GPSManager gpsManager
SensorManager sensorManager
double myHeading = Double.NaN
String services = ``
Sensor sensor
Runnable task
LocationChangeListener locListener
SensorEventListener orientationListener
Detailed Description
Definition at line 19 of file Announcer.java.
Constructor & Destructor Documentation
pt.lsts.asa.comms.Announcer.Announcer (IMCManager imm, String broadcast, String multicast)
Definition at line 86 of file Announcer.java.
References pt.lsts.asa.comms.Announcer.imm.
Member Function Documentation
void pt.lsts.asa.comms.Announcer.generateAnnounce ()
This function can be called to (re)generate the Announce message sent by the console
Definition at line 159 of file Announcer.java.
References pt.lsts.asa.managers.IMCManager.getLocalId(), pt.lsts.asa.util.MUtil.getLocalIpAddress(), and pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce().
Referenced by pt.lsts.asa.comms.Announcer.start().
void pt.lsts.asa.comms.Announcer.setBroadcastAddress (String addr)
Definition at line 121 of file Announcer.java.
void pt.lsts.asa.comms.Announcer.start ()
Definition at line 95 of file Announcer.java.
References pt.lsts.asa.managers.GPSManager.addListener(), pt.lsts.asa.comms.Announcer.generateAnnounce(), pt.lsts.asa.ASA.getGpsManager(), pt.lsts.asa.ASA.getInstance(), pt.lsts.asa.ASA.getPrefs(), pt.lsts.asa.ASA.getSensorManager(), and pt.lsts.asa.util.AccuTimer.start().
Referenced by pt.lsts.asa.ASA.start().
void pt.lsts.asa.comms.Announcer.stop ()
Definition at line 115 of file Announcer.java.
References pt.lsts.asa.managers.GPSManager.removeListener(), and pt.lsts.asa.util.AccuTimer.stop().
Referenced by pt.lsts.asa.ASA.pause().
void pt.lsts.asa.comms.Announcer.updateHeadingOnAnnounce () [private]
Definition at line 142 of file Announcer.java.
References pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.getPrefs().
void pt.lsts.asa.comms.Announcer.updateLocationOnAnnounce () [private]
Definition at line 125 of file Announcer.java.
References pt.lsts.asa.managers.GPSManager.getCurrentLocation(), pt.lsts.asa.ASA.getGpsManager(), pt.lsts.asa.ASA.getInstance(), and pt.lsts.asa.ASA.getPrefs().
Referenced by pt.lsts.asa.comms.Announcer.generateAnnounce().
Member Data Documentation
IMCMessage pt.lsts.asa.comms.Announcer.announce [private]
Definition at line 27 of file Announcer.java.
final String pt.lsts.asa.comms.Announcer.ANNOUNCE_ADDR = `224.0.75.69` [static]
Definition at line 21 of file Announcer.java.
final long pt.lsts.asa.comms.Announcer.ANNOUNCE_DELAY = 10000 [static]
Definition at line 24 of file Announcer.java.
final int pt.lsts.asa.comms.Announcer.ANNOUNCE_PORT = 30100 [static]
Definition at line 23 of file Announcer.java.
AccuTimer pt.lsts.asa.comms.Announcer.at [private]
Definition at line 31 of file Announcer.java.
String pt.lsts.asa.comms.Announcer.broadcastAddress [private]
Definition at line 29 of file Announcer.java.
final boolean pt.lsts.asa.comms.Announcer.DEBUG = false [static]
Definition at line 25 of file Announcer.java.
int pt.lsts.asa.comms.Announcer.gpsAddListenerCounter = 0 [private]
Definition at line 32 of file Announcer.java.
GPSManager pt.lsts.asa.comms.Announcer.gpsManager [private]
Definition at line 33 of file Announcer.java.
IMCManager pt.lsts.asa.comms.Announcer.imm [private]
Definition at line 28 of file Announcer.java.
Referenced by pt.lsts.asa.comms.Announcer.Announcer().
LocationChangeListener pt.lsts.asa.comms.Announcer.locListener [private]
Initial value:
= new LocationChangeListener() {
        @Override
        public void onLocationChange(Location location) {
            updateLocationOnAnnounce();
        }
    }
Definition at line 67 of file Announcer.java.
String pt.lsts.asa.comms.Announcer.multicastAddress [private]
Definition at line 30 of file Announcer.java.
double pt.lsts.asa.comms.Announcer.myHeading = Double.NaN [private]
Definition at line 36 of file Announcer.java.
SensorEventListener pt.lsts.asa.comms.Announcer.orientationListener [private]
Initial value:
= new SensorEventListener() {
        @Override
        public void onSensorChanged(SensorEvent event) {
            myHeading = event.values[0];
            updateHeadingOnAnnounce();
        }
        @Override
        public void onAccuracyChanged(Sensor sensor, int accuracy) {
        }
    }
Definition at line 74 of file Announcer.java.
Sensor pt.lsts.asa.comms.Announcer.sensor [private]
Definition at line 38 of file Announcer.java.
SensorManager pt.lsts.asa.comms.Announcer.sensorManager [private]
Definition at line 34 of file Announcer.java.
String pt.lsts.asa.comms.Announcer.services = `` [private]
Definition at line 37 of file Announcer.java.
final String pt.lsts.asa.comms.Announcer.TAG = `Announcer` [static]
Definition at line 20 of file Announcer.java.
Runnable pt.lsts.asa.comms.Announcer.task [private]
Initial value:
= new Runnable() {
        @Override
        public void run() {
            boolean announcePosition = ASA.getInstance().getPrefs()
                    .getBoolean("announcePosition", true);
            if (DEBUG)
                Log.i(TAG, announce.toString());
            if (imm.getListener() == null) {
                gpsManager.removeListener(locListener);
                gpsAddListenerCounter = 0;
                return;
            }
            if (gpsAddListenerCounter == 0 && announcePosition) {
                gpsManager.addListener(locListener);
            } else if (gpsAddListenerCounter == 2) {
                gpsManager.removeListener(locListener);
            }
            gpsAddListenerCounter = (gpsAddListenerCounter + 1) %
       4;
            updateLocationOnAnnounce();
            for (int i = 0; i < 5; i++) {
                imm.send(broadcastAddress, ANNOUNCE_PORT + i,
      announce);
                imm.send(multicastAddress, ANNOUNCE_PORT + i,
      announce);
            }
        }
    }
Definition at line 40 of file Announcer.java.
The documentation for this class was generated from the following file:
src/pt/lsts/asa/comms/Announcer.java