pt.lsts.asa.sys.Sys Class Reference
Public Member Functions
boolean isError ()
void setError (boolean error)
boolean isConnected ()
void setConnected (boolean mConnected)
String getAddress ()
void setAddress (String address)
int getPort ()
void setPort (int port)
String getName ()
void setName (String name)
int getId ()
void setId (int id)
String getType ()
double[] getLLD ()
void setLLD (double[] lLD)
double[] getNED ()
void setNED (double[] nED)
double[] getRPY ()
void setRPY (double[] rPY)
String getRefMode ()
void setRefMode (String refMode)
LatLng getLatLng ()
void setLatLng (LatLng latLng)
float getPsi ()
void setPsi (float psi)
Marker getMaker ()
void setMaker (Marker maker)
Sys (String address, int port, String name, int id, String type, boolean connected, boolean error)
Public Attributes
long lastMessageReceived
Private Attributes
String mAddress
int mPort
String mName
int mId
String mType
double[] LLD = { 0.0, 0.0, 0.0 }
double[] NED = { 0.0, 0.0, 0.0 }
double[] RPY = { 0.0, 0.0, 0.0 }
LatLng latLng = new LatLng(0,0)
float psi = 0.0f
Marker maker =null
String refMode
Detailed Description
Definition at line 6 of file Sys.java.
Constructor & Destructor Documentation
pt.lsts.asa.sys.Sys.Sys (String address, int port, String name, int id, String type, boolean connected, boolean error)
Definition at line 139 of file Sys.java.
Member Function Documentation
String pt.lsts.asa.sys.Sys.getAddress ()
Definition at line 47 of file Sys.java.
References pt.lsts.asa.sys.Sys.mAddress.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), pt.lsts.asa.managers.IMCManager.sendToSys(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
int pt.lsts.asa.sys.Sys.getId ()
Definition at line 71 of file Sys.java.
References pt.lsts.asa.sys.Sys.mId.
Referenced by pt.lsts.asa.util.IMCUtils.isMsgFromActive(), and pt.lsts.asa.subscribers.HeartbeatVibratorIMCSubscriber.onReceive().
LatLng pt.lsts.asa.sys.Sys.getLatLng ()
Definition at line 115 of file Sys.java.
References pt.lsts.asa.sys.Sys.latLng.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos(), and pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
double [] pt.lsts.asa.sys.Sys.getLLD ()
Definition at line 83 of file Sys.java.
References pt.lsts.asa.sys.Sys.LLD.
Marker pt.lsts.asa.sys.Sys.getMaker ()
Definition at line 131 of file Sys.java.
References pt.lsts.asa.sys.Sys.maker.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos(), and pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
String pt.lsts.asa.sys.Sys.getName ()
Definition at line 63 of file Sys.java.
References pt.lsts.asa.sys.Sys.mName.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos(), pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng(), and pt.lsts.asa.activities.MainActivity.test2().
double [] pt.lsts.asa.sys.Sys.getNED ()
Definition at line 91 of file Sys.java.
References pt.lsts.asa.sys.Sys.NED.
int pt.lsts.asa.sys.Sys.getPort ()
Definition at line 55 of file Sys.java.
References pt.lsts.asa.sys.Sys.mPort.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), and pt.lsts.asa.managers.IMCManager.sendToSys().
float pt.lsts.asa.sys.Sys.getPsi ()
Definition at line 123 of file Sys.java.
References pt.lsts.asa.sys.Sys.psi.
Referenced by pt.lsts.asa.fragments.GmapFragment.updateActiveSysMarker().
String pt.lsts.asa.sys.Sys.getRefMode ()
Definition at line 107 of file Sys.java.
References pt.lsts.asa.sys.Sys.refMode.
double [] pt.lsts.asa.sys.Sys.getRPY ()
Definition at line 99 of file Sys.java.
References pt.lsts.asa.sys.Sys.RPY.
String pt.lsts.asa.sys.Sys.getType ()
Definition at line 79 of file Sys.java.
References pt.lsts.asa.sys.Sys.mType.
Referenced by pt.lsts.asa.fragments.SystemListFragment.addSysStatus(), pt.lsts.asa.fragments.SystemListFragment.colorItems(), and pt.lsts.asa.fragments.SystemListFragment.filterSys().
boolean pt.lsts.asa.sys.Sys.isConnected ()
Definition at line 39 of file Sys.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.colorItems(), pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
boolean pt.lsts.asa.sys.Sys.isError ()
Definition at line 31 of file Sys.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.colorItems(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
void pt.lsts.asa.sys.Sys.setAddress (String address)
Definition at line 51 of file Sys.java.
void pt.lsts.asa.sys.Sys.setConnected (boolean mConnected)
Definition at line 43 of file Sys.java.
void pt.lsts.asa.sys.Sys.setError (boolean error)
Definition at line 35 of file Sys.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive().
void pt.lsts.asa.sys.Sys.setId (int id)
Definition at line 75 of file Sys.java.
void pt.lsts.asa.sys.Sys.setLatLng (LatLng latLng)
Definition at line 119 of file Sys.java.
References pt.lsts.asa.sys.Sys.latLng.
Referenced by pt.lsts.asa.fragments.GmapFragment.setActiveSysLatLng().
void pt.lsts.asa.sys.Sys.setLLD (double[] lLD)
Definition at line 87 of file Sys.java.
void pt.lsts.asa.sys.Sys.setMaker (Marker maker)
Definition at line 135 of file Sys.java.
References pt.lsts.asa.sys.Sys.maker.
Referenced by pt.lsts.asa.fragments.GmapFragment.addMarkerToPos().
void pt.lsts.asa.sys.Sys.setName (String name)
Definition at line 67 of file Sys.java.
void pt.lsts.asa.sys.Sys.setNED (double[] nED)
Definition at line 95 of file Sys.java.
void pt.lsts.asa.sys.Sys.setPort (int port)
Definition at line 59 of file Sys.java.
void pt.lsts.asa.sys.Sys.setPsi (float psi)
Definition at line 127 of file Sys.java.
References pt.lsts.asa.sys.Sys.psi.
Referenced by pt.lsts.asa.fragments.GmapFragment.setActiveSysPsi().
void pt.lsts.asa.sys.Sys.setRefMode (String refMode)
Definition at line 111 of file Sys.java.
References pt.lsts.asa.sys.Sys.refMode.
void pt.lsts.asa.sys.Sys.setRPY (double[] rPY)
Definition at line 103 of file Sys.java.
Member Data Documentation
long pt.lsts.asa.sys.Sys.lastMessageReceived
Definition at line 12 of file Sys.java.
Referenced by pt.lsts.asa.subscribers.SystemListIMCSubscriber.onReceive(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
LatLng pt.lsts.asa.sys.Sys.latLng = new LatLng(0,0) [private]
Definition at line 19 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getLatLng(), and pt.lsts.asa.sys.Sys.setLatLng().
double [] pt.lsts.asa.sys.Sys.LLD = { 0.0, 0.0, 0.0 } [private]
Definition at line 14 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getLLD().
String pt.lsts.asa.sys.Sys.mAddress [private]
Definition at line 8 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getAddress().
Marker pt.lsts.asa.sys.Sys.maker =null [private]
Definition at line 21 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getMaker(), and pt.lsts.asa.sys.Sys.setMaker().
int pt.lsts.asa.sys.Sys.mId [private]
Definition at line 11 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getId().
String pt.lsts.asa.sys.Sys.mName [private]
Definition at line 10 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getName().
int pt.lsts.asa.sys.Sys.mPort [private]
Definition at line 9 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getPort().
String pt.lsts.asa.sys.Sys.mType [private]
Definition at line 13 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getType().
double [] pt.lsts.asa.sys.Sys.NED = { 0.0, 0.0, 0.0 } [private]
Definition at line 16 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getNED().
float pt.lsts.asa.sys.Sys.psi = 0.0f [private]
Definition at line 20 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getPsi(), and pt.lsts.asa.sys.Sys.setPsi().
String pt.lsts.asa.sys.Sys.refMode [private]
Definition at line 24 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getRefMode(), and pt.lsts.asa.sys.Sys.setRefMode().
double [] pt.lsts.asa.sys.Sys.RPY = { 0.0, 0.0, 0.0 } [private]
Definition at line 17 of file Sys.java.
Referenced by pt.lsts.asa.sys.Sys.getRPY().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/sys/Sys.java