pt.lsts.asa.util.StringUtils Class Reference
Static Public Member Functions
static String getCamUrl (VideoView videoView)
static String getAirCamUrl (VideoView videoView)
static String getAxisUrl (VideoView videoView)
static String validateResolution (String resolution, VideoView videoView)
static String getVideoViewResolution (VideoView videoView)
static String removeSysExtraInfo (String sysName)
static String timeSinceLastMessage (long t1, long t2)
static boolean validateSetting (String setting)
Detailed Description
Created by jloureiro on 18-12-2014.
Definition at line 12 of file StringUtils.java.
Member Function Documentation
static String pt.lsts.asa.util.StringUtils.getAirCamUrl (VideoView videoView) [static]
Definition at line 28 of file StringUtils.java.
References pt.lsts.asa.settings.Settings.getString().
Referenced by pt.lsts.asa.util.StringUtils.getCamUrl().
static String pt.lsts.asa.util.StringUtils.getAxisUrl (VideoView videoView) [static]
Definition at line 57 of file StringUtils.java.
References pt.lsts.asa.settings.Settings.getString(), and pt.lsts.asa.util.StringUtils.validateResolution().
Referenced by pt.lsts.asa.util.StringUtils.getCamUrl().
static String pt.lsts.asa.util.StringUtils.getCamUrl (VideoView videoView) [static]
Definition at line 14 of file StringUtils.java.
References pt.lsts.asa.util.StringUtils.getAirCamUrl(), pt.lsts.asa.util.StringUtils.getAxisUrl(), and pt.lsts.asa.settings.Settings.getString().
Referenced by pt.lsts.asa.fragments.VideoViewFragment.setVideoViewListeners(), and pt.lsts.asa.fragments.VideoViewFragment.startVideo().
static String pt.lsts.asa.util.StringUtils.getVideoViewResolution (VideoView videoView) [static]
Definition at line 88 of file StringUtils.java.
Referenced by pt.lsts.asa.util.StringUtils.validateResolution().
static String pt.lsts.asa.util.StringUtils.removeSysExtraInfo (String sysName) [static]
Definition at line 95 of file StringUtils.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.colorItems(), pt.lsts.asa.fragments.SystemListFragment.selectActiveSystem(), and pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
static String pt.lsts.asa.util.StringUtils.timeSinceLastMessage (long t1, long t2) [static]
Definition at line 100 of file StringUtils.java.
Referenced by pt.lsts.asa.fragments.SystemListFragment.showMoreInfo().
static String pt.lsts.asa.util.StringUtils.validateResolution (String resolution, VideoView videoView) [static]
Definition at line 71 of file StringUtils.java.
References pt.lsts.asa.util.StringUtils.getVideoViewResolution().
Referenced by pt.lsts.asa.util.StringUtils.getAxisUrl().
static boolean pt.lsts.asa.util.StringUtils.validateSetting (String setting) [static]
Definition at line 134 of file StringUtils.java.
Referenced by pt.lsts.asa.settings.Profile.loadSetting().
The documentation for this class was generated from the following file:
src/pt/lsts/asa/util/StringUtils.java